### ISSUE TITLE
Regression on silero-vad v3.1 onnx model

### ISSUE THREAD

**Issue by 7r3nzy** [sonos/tract#1030]
I tried different versions it looks like the issue started happening since `0.18.0`. the model was working fine till `0.17.9` 
```
Error Failed analyse for node #127 "If_33" If

Caused by:
    0: Infering facts
    1: Failed analyse for node #1 "Squeeze_35" Squeeze13
    2: Infering facts
    3: Applying rule outputs[0].shape == 1,1,1792
    4: Unifying shapes S,S,S and 1,1,1792
    5: Impossible to unify Sym(Symbol('S', 1)) with Val(1).
```

**Comment by kali** [comment]
I think this one is typical over specification of interfaces. Starting with 0.18, tract takes into account input and outputs in ONNX models. Before that, a bug was preventing them to be parsed.

So if you change an input spec, it's often necessary to cancel the output spec. On the command line, the --onnx-ignore-output-shape will do just that. On the API, you need to cancel them by calling `with_output_fact(0, Default::default())`, etc. right after loading the model.

**Comment by 7r3nzy** [comment]
@kali thank you for looking into it. So I have tried `--onnx-ignore-output-shapes` 
as:

```bash
tract silero_vad.onnx --onnx-ignore-output-shapes
```

Now I am getting this error:

```
Error at stage analyse

    Caused by:
        0: Failed analyse for node #680 "LSTM_589" LSTM
        1: Failed analyse for node #680 "LSTM_589" LSTM
        2: Infering facts
        3: Wrong output number. Rules expect 2, node has 3.
```

**Comment by kali** [comment]
Can you give me the onnx file ?

**Comment by 7r3nzy** [comment]
Sure! [here it is](https://github.com/snakers4/silero-vad/archive/refs/tags/v3.1.tar.gz). Path inside the tar.gz is `silero-vad/files/silero_vad.onnx`.

**Comment by kali** [comment]
I think #1037 (I batched several issues together) fixed this one. v4 will need a bit more work.

**Comment by 7r3nzy** [comment]
Thanks a bunch!
