### ISSUE TITLE
Problems with input types

### ISSUE THREAD

**Issue by giorgostheo** [sonos/tract#1080]
Hey!

I am trying to infer an onnx model that get a multidimensional array and an integer as input.

When I try to cargo run, I get the following (line 517 is where the second input is specified - the i64).

```
Caused by:
    Tensor datum type error: tensor is TDim, accessed as I64', src/structsnew.rs:517:65
```

Are you familiar with this by chance?

**Comment by kali** [comment]
Hey, sure, I can probably help, but I need to see the model, and a repro, ideally with tract command line or some simple main.rs.

**Comment by giorgostheo** [comment]
Thanks for the quick response

The problems is with the second input. Does this help?

```
let model = tract_onnx::onnx()
            // load the model
            .model_for_path("model1.onnx").unwrap()
            .with_input_fact(0, f32::fact([1,10,4]).into()).unwrap()
            .with_input_fact(1, i64::fact([1]).into()).unwrap()

            .into_runnable().unwrap();

let inp1: Tensor = tract_ndarray::Array3::from_shape_vec((1, 10,4), data.iter().map(|&x| x as f32).collect()).unwrap().into();
let inp2: Tensor = tract_ndarray::Array::from_shape_vec(1, vec![10 as i64]).unwrap().into();

let result = model.run(tvec!(inp1.into(), inp2.into())).unwrap(); <- this errors out

println!("result: {:?}", result);
panic!();
```

**Comment by kali** [comment]
it's going to be difficult if you can't share the model (it does not have to be trained, and you can reach me at first-name dot last-name at sonos dot com if it helps)

**Comment by giorgostheo** [comment]
Unfortunately the model is trained on proprietary data, that is why I cannot share it.

I will try to either create a copy that is not trained, or train it on some open dataset. 

In the meantime, do you have any hunches about what might be the problem? Does "TDim" ring a bell?

**Comment by giorgostheo** [comment]
Tried both but no luck. `vec!([10.to_dim()])` errors since there is no Datum trait.
