### ISSUE TITLE
Invalid AxesMappings for some instances of einsum 

### ISSUE THREAD

**Issue by alexander-camuto** [sonos/tract#1083]
Heya @kali have started implementing / fanning out from `Einsum` in ezkl and the reduction of many complex operations to a single notation / op has been much appreciated :) 

However I'm finding that certain models (in particular some deeper networks) generate invalid `AxesMapping` strings for matrix multiplication. For instance I'll find that when displayed, I get equations of the form `mk,k->mn`, whereby the output indices have indices not represented in the inputs. From what I can tell this is also invalid notation in numpy / pytorch and unless I'm mistaken these are generally invalid equations in Einstein notation. 

You can reproduce this issue using https://github.com/alexander-camuto/einsum-issue-repro and running: 

```rust 

RUST_LOG=trace cargo run 

```

It will end by printing the einsum notation of the matmul node.

**Comment by kali** [comment]
Repo is private, mate.

**Comment by alexander-camuto** [comment]
@kali my bad 🤦fixed

**Comment by kali** [comment]
So tract is happy with `mk,k->mn`. Semantics for n is a just trivial (dim=1) axis in the output.

**Comment by alexander-camuto** [comment]
Gotcha -- so unrepresented dims in the output are always mapped to "n" ? or is it any unrepresented index (could be any letter) that gets mapped to 1 ?

**Comment by kali** [comment]
Any letter only present in the output can be mapped to a trivial axis of 1. There is no specific semantics attached to any actual letter (even if i try to use m,k and n to point to the axis in the gemm way). You may want to look at helpers in as_matmul and codegen to figure out which axis play which role. (in these functions, m,k and n refer to the gemm convention, but can point to axes labelled, a, b and c or whatever).

**Comment by alexander-camuto** [comment]
Amazing thank you for clarifying.
