### ISSUE TITLE
`TopK` with dynamic K

### ISSUE THREAD

**Issue by alexander-camuto** [sonos/tract#1091]
Models with `TopK` nodes fail to type. 

A sample error: 

```bash
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Failed analyse for node #717 "TopK_717" Topk

Caused by:
    0: Infering facts
    1: Applying rule inputs[1].datum_type == I64
    2: Impossible to unify TDim with I64.', src/main.rs:12:36

```

A repo to reproduce the issue (I swear it is public this time): https://github.com/alexander-camuto/topk-issue-repro 

To reproduce the issue this time you need to download the model at https://github.com/onnx/models/raw/main/vision/object_detection_segmentation/ssd/model/ssd-10.onnx to ./src/network.onnx 

then run 

```bash
RUST_LOG=trace cargo run 
```

**Comment by alexander-camuto** [comment]
as always ty for the tip :)

**Comment by kali** [comment]
When I implemented TopK a couple of weeks ago, it was pretty clear that K would always be constant. This "always" was a pretty short-lived one... I'm going to try to do this soon-ish.

**Comment by JernKunpittaya** [comment]
Hi, we are trying to implement stats function using ezkl, like percentile and median stuffs, so would be nice to have this sort feature :) Thanks!
