### ISSUE TITLE
"Greater does not support F16" when using model with `f16` weights

### ISSUE THREAD

**Issue by SludgePhD** [sonos/tract#1103]
Model file: [face_landmarks_detector_f16.onnx.zip](https://github.com/sonos/tract/files/11655625/face_landmarks_detector_f16.onnx.zip)

Attempting to perform inference with this model results in an error like this:

```
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Evaluating #4 "model_5_model_4_model_3_p_re_lu_126_add;model_5_model_4_model_3_p_re_lu_126_Relu;model_5_model_4_model_3_p_re_lu_126_Neg_1;model_5_model_4_model_3_p_re_lu_126_Relu_1;model_5_model_4_model_3_p_re_lu_126_mul1.test" Greater

Caused by:
    Greater does not support F16'
```

I am not quite sure if this is a bug, should this node have been converted during optimzation? If not, is there some way to have tract convert the `f16` weights to `f32` on import (I'm mostly interested in the space savings from `f16` weights)?

**Comment by kali** [comment]
It's a bug. f16 is semi-experimental in tract, so there was another one I fixed on the Pad operator, but the network seems to work now (as in not crashing).

 Please try the branch and tell me how it goes.

**Comment by SludgePhD** [comment]
That does fix it, thanks! The network doesn't seem to work correctly though, when compared to the f32 version. This might have happened during conversion though.

**Comment by kali** [comment]
Are you aware that tract can handle the f32->f16 itself ? `--half-floats` will do it for you or https://github.com/sonos/tract/blob/main/ffi/src/lib.rs#L795 for an example with the API. Note that some networks do not handle halving right, sometimes they can saturate the f16 range. You may need to dichotomize the network to figure out where it diverges.

**Comment by SludgePhD** [comment]
If I use `HalfTranslator` on the original model ([face_landmarks_detector.onnx.zip](https://github.com/sonos/tract/files/11681405/face_landmarks_detector.onnx.zip)) I get this error when running inference:

```
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Evaluating #7 "model_5/model_4/model_3/p_re_lu_126/add;model_5/model_4/model_3/p_re_lu_126/Relu;model_5/model_4/model_3/p_re_lu_126/Neg_1;model_5/model_4/model_3/p_re_lu_126/Relu_1;model_5/model_4/model_3/p_re_lu_126/mul1.test" Greater

Caused by:
    Tensor datum type error: tensor is F32, accessed as F16'
```

**Comment by SludgePhD** [comment]
I've also confirmed that my originally converted model infers correctly with onnxruntime (via https://github.com/pykeio/ort), so it looks like there are still some bugs left here

**Comment by kali** [comment]
Good to know. I'll try to have a look soon-ish.
