### ISSUE TITLE
Backwards compatibility between 0.19.x and 0.20.x is broken

### ISSUE THREAD

**Issue by cospectrum** [sonos/tract#1125]
Hi! Just noticed that yolov8 is no longer valid in tract-onnx 0.20.
```
Error: running pass PushSliceUp

Caused by:
    0: Calling slice on #410 "/model.22/Concat_4" Concat
    1: in output_facts invocation for /model.22/Concat_4.split-over-1.64..65.slice-1.64..65
    2: Condition failed: `end <= len` (65 vs 1)
```

**Comment by kali** [comment]
Thanks, that was of course not intentional. Can you link the onnx file you're using and the input fact ?

**Comment by cospectrum** [comment]
> Thanks, that was of course not intentional. Can you link the onnx file you're using and the input fact ?

[yolov8n.onnx.zip](https://github.com/sonos/tract/files/12052922/yolov8n.onnx.zip)
For example, the smallest detection model from [ultralytics](https://github.com/ultralytics/ultralytics). 
The input fact is (1, 3, 640, 640, F32).
```
Error: running pass PushSliceUp

Caused by:
    0: Calling slice on #410 "/model.22/Concat_3" Concat
    1: in output_facts invocation for /model.22/Concat_3.split-over-1.64..144.slice-1.64..144
    2: Condition failed: `end <= len` (144 vs 80)
```

**Comment by kali** [comment]
Hey, sorry for the long delay. Could you please check if #1134 fixes your issue ?
