### ISSUE TITLE
Quantized model is not compatible

### ISSUE THREAD

**Issue by mush42** [sonos/tract#1153]
Hi,

I have a model that works perfectly with `Tract`, but when quantizing the model using `intel neural compressor` Tract can no longer run the model. 

Tract fails with the following error:

```bash

thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Translating node #20 "/transformer/Add_quant" Unimplemented(QLinearAdd) ToTypedTranslator

Caused by:
    Operator can not be made a TypedOp.', src\main.rs:47:10

```

Does Tract support **quantized** models? If so what quantization procedure should I use?

Best

**Comment by kali** [comment]
I mean for tract to support some "standard" quantization (i8/u8, linear). A lot of stuff is already there, some networks are working. But it's not at the level of float support, in robustness and in performance.

On top of this, QLinearAdd is not (yet ?) par of ONNX, it is part of the contrib operator set. tract has no support for these operators yet. I feel like ONNX has been lagging in supporting quantized operations.

NNEF tract support may be more robust: we bet on NNEF a couple years ago, use it a lot internally so the code is more mature. Sadly, it looks like we bet on the wrong horse, as TensorFlowLite seems to be what everybody is doing these day for quantized models. So we started working on tfilte very recently, and are making progress, but... it's not great yet.

Sorry not to be able to give you a more clear-cut answer.

**Comment by mush42** [comment]
So, does NNEF support quantized opts? can you guide me to some relevant resources for converting ONNX to NNEF?

**Comment by mush42** [comment]
I want to add that Tract is really a game changer for deploying models. I was surprised when my model built successfully for the `wasm32-wasi` target. In effect, I can ship my model as a single executable module that runs on any platform for which a `wasm` runtime exists, which, in the last count, include most platforms, including MCUs.

So, kudos!

**Comment by kali** [comment]
Thanks for the kind words :)

NNEF does support quantization, but I am not sure you will find lots of resource for automatic conversion from onnx to nnef, specifically for quantized network. So in the current state of thing, I'm not sure I have anything better to recommend that sticking with onnxruntime. I hope I can make TensorLlowLite -> tract a viable option in a couple of months.
