### ISSUE TITLE
New `Squeeze` (ONNX opset >= 13)

### ISSUE THREAD

**Issue by alexander-camuto** [sonos/tract#1154]
A user of ours ran into a set of models which tract fails to analyze. 

Here is the output for one such model using the `tract` cli built from the latest commit ([0ee4781](https://github.com/sonos/tract/commit/0ee47819e0c657badf6055019adde9aa1eb9fde7) at time of writing): 

```bash 
┏ 0 Source input
┃   ━━━ batch_size,128,F32
┣┻ 8 Mul /Mul
┃   ━━━ batch_size,128,F32
┣┻┻ 9 Gemm /mlp_1/layers/layers.0/fc/Gemm
┃   ━━━ batch_size,64,F32
┣ 10 Clip /mlp_1/layers/layers.0/activation/Relu
┣┻┻ 11 Gemm /mlp_1/layers/layers.1/fc/Gemm
┃   ━━━ batch_size,32,F32
┣ 12 Clip /mlp_1/layers/layers.1/activation/Relu
┣┻┻ 13 Gemm /lin_layer_1/fc/Gemm
┃   ━━━ batch_size,1,F32
┣ 14 Squeeze13 /Squeeze
    ━━━ ..,?
[2023-08-14T19:17:14.078176000Z ERROR tract] Error at stage analyse
    
    Caused by:
        0: Failed analyse for node #14 "/Squeeze" Squeeze13
        1: Failed analyse for node #14 "/Squeeze" Squeeze13
        2: Infering facts
        3: Wrong input number. Rules expect 2, node has 1.

```

You can find a zip with all the models in question at https://github.com/zkonduit/ezkl/issues/411 .

To reproduce the issue simply run `tract <MODEL IN QUESTION>` with one of the files in the zip.

**Comment by kali** [comment]
Squeeze now takes the axes to remove as a second input instead of a parameter. Will fix.

In the meantime, serializing the model with ONNX operator set <13 may be a workaround.

**Comment by kali** [comment]
OK, more subtle than I thought. Second input is already implemented, but it is optional (tract code assume it is required). When it is optional, squeeze remove all 1-dim indexed.

I will implement it. But I strongly recommend not using this feature, it is an absolutely terrible idea. This network has a variable batch size, as long as it will be using a symbol, it will not remove the axis. If something sets the batch_size to 1, then the axis will be removed. This is bad.

**Comment by alexander-camuto** [comment]
ty so much
