### ISSUE TITLE
thread 'main' panicked at 'index out of bounds: the len is 0 but the index is 0'

### ISSUE THREAD

**Issue by alexander-camuto** [sonos/tract#1177]
Have a particular model here (which executes in pytorch and onnxruntime fine) but fails to analyze as an Einsum op within tract 

```bash
thread 'main' panicked at 'index out of bounds: the len is 0 but the index is 0', hir/src/ops/matmul.rs:69:47
```

[network.onnx.zip](https://github.com/sonos/tract/files/12506432/network.onnx.zip)

Here is the netron graph 

<img width="413" alt="image" src="https://github.com/sonos/tract/assets/45801863/0a3292aa-3a34-4d00-85eb-1e4c04ec284f">

And have confirmed that the graph is (ok) onnx: 

```python
import onnx
onnx_model = onnx.load("networkonnx")
onnx.checker.check_model(onnx_model)

```

**Comment by kali** [comment]
Is #1192 fixing ?

**Comment by alexander-camuto** [comment]
yes confirmed it is !
