### ISSUE TITLE
Source node without a determined fact on a simple model with a single symbolic dim

### ISSUE THREAD

**Issue by alexander-camuto** [sonos/tract#1238]
Heya ! It's been a while. 

I have a very simple model -- created by splitting a larger model using `onnx.utils.extract_model` that fails to analyze if an explicit input fact isn't provided with: 

```rust
[2023-10-22T14:10:04.409062000Z ERROR tract] Error at stage type
    
    Caused by:
        0: Translating node #0 "/conv1/Conv_output_0" Source ToTypedTranslator
        1: Source node without a determined fact. Help: provide explicit input facts to your model.

```

The model only has a single symbolic dim `batch_size` and is relatively simple so (I don't think) this would be expected behaviour: 

<img width="287" alt="image" src="https://github.com/sonos/tract/assets/45801863/5b79ae56-5fbd-4b60-ae59-5aaa1be94dc8">

model is attached below as a zip: 

[network_split_1.onnx.zip](https://github.com/sonos/tract/files/13063435/network_split_1.onnx.zip)

to reproduce run `tract network_split_1.onnx`. 
`tract network_split_1.onnx --input 1,1,1,1,F32` succeeds however.

**Comment by kali** [comment]
First I though that the extract_model script may erase the types, but no, it's tract who does. At the end of the (big) function that build the model, we copy all the types from the value_info structure in the onnx file to the InferenceFact in the output of the matched nodes. And I was erasing the type while doing so. Not sure why. I'm gonna remove it and see what breaks.
