### ISSUE TITLE
Error while reading with into_optimized quant models

### ISSUE THREAD

**Issue by igor-yusupov** [sonos/tract#1329]
I made a quantization for encoder and decoder from transformer. it works OK without calling into_optimized, but it is obviously running slow.

with into_optimized I got errors:

encoder:
```
called `Result::unwrap()` on an `Err` value: Failed analyse for node #213 "/encoder/layers.0/self_attn/ConstantOfShape" ConstantOfShape

Caused by:
    0: Infering facts
    1: Applying rule outputs[0].shape[0] == Val(1)
    2: Impossible to unify Sym(unk__3) with Val(1).
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

decoder:
```
called `Result::unwrap()` on an `Err` value: Failed analyse for node #446 "/decoder/layers.0/self_attn/ConstantOfShape" ConstantOfShape

Caused by:
    0: Infering facts
    1: Applying rule outputs[0].shape[0] == Val(1)
    2: Impossible to unify Sym(unk__3) with Val(1).
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

encoder: https://www.dropbox.com/scl/fi/qzdjxh0t6wgokmmrvb7a6/encoder.quant.onnx?rlkey=mp06v3xw2imq1ips1ligh5yu6&dl=0
decoder: https://www.dropbox.com/scl/fi/asrlmk15242b1dqbm9qvn/decoder.quant.onnx?rlkey=2i1f4ek50h25cyil0jhr70rqc&dl=0

**Comment by kali** [comment]
Please check out the attached branch (there is a bit of a bold move with ignoring all unk__ symbols from onnx and another patch)

**Comment by igor-yusupov** [comment]
Thank you! Yes, it works, thank you! But it seems that quant models run slower than standard onnx models

**Comment by igor-yusupov** [comment]
I got it, thank you. I hope you will be able to use quantized data similarly in onnxruntime, because it gives a very steep speed boost and also allows you to reduce the size of the model, which makes it easier to deploy to devices.
