### ISSUE TITLE
Performance regression in 0.21

### ISSUE THREAD

**Issue by carsten-wenderdel** [sonos/tract#1330]
While benchmarking my own project, I noticed a performance regression of roughly 10% when updating `tract` from 0.20.21 to 0.21.1.

To narrow things down, I changed the `Cargo.toml` file and used `tract` as a local dependency. Then using `git bisect` I tried different commits to find the regression. It seems to be the following commit: c00e5e6. The previous commit (97d18f3) works fine.

The used onnx files are very small, I have attached them here. [onnx-files.zip](https://github.com/sonos/tract/files/14220316/onnx-files.zip)
They are used for inference; before usage `with_input_fact` and `into_optimized` are executed to allow batching.

My hardware is a M1 MacBook Air.
Operating system is MacOS 14.2.1.
Rust version is 1.76.0 stable.

It's possible to recreate the performance regression by downloading my project https://github.com/carsten-wenderdel/wildbg/tree/tract-performance and putting it in the same folder that `tract` has been put in. Then executing the following line in the repo's root directory will show the benchmarking times:
```cargo bench -p benchmarks --bench rollout_bench```

**Comment by kali** [comment]
Nice report, small models make different performance issue pop out :) I found a couple of unnecessary TDim cloning sprinkled everywhere, and I think it will help your networks.

**Comment by carsten-wenderdel** [comment]
Great! I tried it out and the performance is as good as the one from 97d18f3, which is also better than 0.20.21.

Thanks a lot, for the quick response and `tract` in general!
