### ISSUE TITLE
simple tree model fails to analyze reduce sum 

### ISSUE THREAD

**Issue by alexander-camuto** [sonos/tract#1345]
Could be that the model format is slight incorrect but a sum node seems to expect an output of size (batch_size,1) but instead has a an output of dim (batch_size) with the summand axis being eliminated. 

Was wondering if failure was to be expected here. 

Attached you'll find the model and the associated error can be replicated using the latest tract 
```bash
cargo install --git https://github.com/sonos/tract tract
# once the install is done run 
tract onnx_model.onnx > tract.tear
```
with expected output error: 
```bash
2024-02-27T13:53:00.394230000Z ERROR tract] Error at stage "type"
    
    Caused by:
        0: Translating node #26 "/_operators.0/ReduceSum" Reduce<Sum> ToTypedTranslator
        1: Output mismatch after rewiring expansion for output #0: expected batch_size,1,TDim got batch_size
```

[onnx_model.onnx.zip](https://github.com/sonos/tract/files/14422980/onnx_model.onnx.zip)

**Comment by kali** [comment]
Heelo there, I observe a bit of a different issue on my side, but after fixing in branch `fix1345` it seems to load. Want to check for me ?

**Comment by alexander-camuto** [comment]
works now ! thank you
