### ISSUE TITLE
Broken link in the blog post "Optimising a neural network for inference" (Sonos Tech Blog)

### ISSUE THREAD

**Issue by Dobiasd** [sonos/tract#1354]
Thanks for this amazing library! Just wanted to let you know, that in the blog post "Optimising a neural network for inference" (https://tech-blog.sonos.com/posts/optimising-a-neural-network-for-inference/) the link to the second post is broken.
- linked URL: https://tech-blog.sonos.com/posts/anatomy-of-efficient-matrix-multipliers/
- actual URL: https://tech-blog.sonos.com/posts/the-anatomy-of-efficient-matrix-multipliers/

**Comment by kali** [comment]
Thank you! It's been fixed.
