### ISSUE TITLE
Do you support onnx extensions?

### ISSUE THREAD

**Issue by kckeiks** [sonos/tract#1372]
I didn't see it in your docs. For reference, https://github.com/microsoft/onnxruntime-extensions.

**Comment by kali** [comment]
No, only ONNX (with a couple of exceptions) is supported.

As far as I can say, these are onnxruntime extensions using a protocol defined by the onnxruntime project, and not ONNX extensions conforming to something defined by the ONNX spec.

tract has comparable semi-internal rust API to define new operators but that's about it.
