### ISSUE TITLE
Xception model Unsupported: OperatorCode: MAX_POOL_2D

### ISSUE THREAD

**Issue by GarethEgerton** [sonos/tract#1402]
I am trying to load a basic Xception model: https://www.tensorflow.org/api_docs/python/tf/keras/applications/Xception

However when loading the model:  
```rust
    let model_result = tract_tflite::tflite()
        .model_for_path(&model_path)
        .and_then(|model| model.into_optimized())
        .and_then(|model| model.into_runnable());
``` 
I'm getting the following error:

```
Error: Translating proto model to model

Caused by:
    0: Parsing op Operator {
           opcode_index: 2,
           inputs: Some(
               [
                   129,
               ],
           ),
           outputs: Some(
               [
                   130,
               ],
           ),
           builtin_options_type: Pool2DOptions,
           builtin_options: Pool2DOptions {
               padding: SAME,
               stride_w: 2,
               stride_h: 2,
               filter_width: 3,
               filter_height: 3,
               fused_activation_function: NONE,
           },
           },
           custom_options: None,
           custom_options_format: FLEXBUFFERS,
           mutating_variable_inputs: None,
           intermediates: None,
       }
    1: Unsupported: OperatorCode {
           deprecated_builtin_code: 17,
           custom_code: None,
           version: 1,
           builtin_code: MAX_POOL_2D,
       }, inputs: [
           1,147,147,128,F32,
       ]
``` 
Do you know if there is any version of tract that supports the MAX_POOL_2D operation used in the Xception model and if there is any way to resolve this error? Any help would be much appreciated :)

**Comment by kali** [comment]
Hello, support for tensroflow lite is not complete, but it is very likely an easy fix: this operator exists in tract, it just needs to be mapped from tflite format. I can have a look.

It would help if you can upload the `.tflite` file.

**Comment by GarethEgerton** [comment]
Thanks for your help @kali, that would be great!
Here is a link to the model: https://drive.google.com/file/d/1dcpTM10jtKdD7e96nAZ1qrIrvybb9c8B/view?usp=sharing

**Comment by kali** [comment]
FYI, #1403 fixes the MAX_POOL but this model manifests another issue. I will have a look.

**Comment by GarethEgerton** [comment]
Amazing, thanks for your support @Kali. I tested again and can see that the MAX_POOL error is resolved with your update, and can also see the new error for the [Xception](https://www.tensorflow.org/api_docs/python/tf/keras/applications/Xception) model which you are referring to:
```
Error: Translating proto model to model

Caused by:
    0: Parsing op Operator {
           opcode_index: 6,
           inputs: Some(
               [
                   225,
                   123,
                   121,
               ],
           ),
           outputs: Some(
               [
                   226,
               ],
           ),
           builtin_options_type: FullyConnectedOptions,
           builtin_options: FullyConnectedOptions {
               fused_activation_function: NONE,
               weights_format: DEFAULT,
               keep_num_dims: false,
               asymmetric_quantize_inputs: false,
           },
           custom_options: None,
           custom_options_format: FLEXBUFFERS,
           mutating_variable_inputs: None,
           intermediates: None,
       }
    1: Opcode is OperatorCode {
           deprecated_builtin_code: 9,
           custom_code: None,
           version: 1,
           builtin_code: FULLY_CONNECTED,
       }
    2: in output_facts invocation for xception/predictions/MatMul;xception/predictions/BiasAdd: EinSum
    3: Condition failed: `inputs.len() == self.axes.input_count()` (3 vs 9)
``` 
Thanks for taking a look at this

**Comment by kali** [comment]
yeah, that's the same one I saw. I will have a look.

**Comment by kali** [comment]
Hey, could you check out the linked branch ? The model now loads fully, can you confirm weather it is producing the expected results ?

**Comment by GarethEgerton** [comment]
I just tested it and confirmed that it loads correctly and also predicts the correct results. Thanks so much for your help!

**Comment by kali** [comment]
0.21.5 contains all these fixes. Closing.
