### ISSUE TITLE
Stray `dbg!()` in several crate versions

### ISSUE THREAD

**Issue by SludgePhD** [sonos/tract#1406]
https://github.com/sonos/tract/blob/5576526b7ddda189d7dbe834f7a14d700022836d/onnx/src/ops/resize.rs#L11

This has made its way into 0.21 crate releases and prints to stderr every time I open an ONNX file.

I suggest using a CI check that fails when the string `dbg!` is encountered in a Rust source file, that typically prevents these issues with essentially zero false positives in most projects.

**Comment by kali** [comment]
Only one of these dbg! is in actual production code, the rest are in tests. I have mixed feeling about removing them. I completely hear you, dbg!() in production code is absolutely not acceptable. On the other hand, it's to my knowledge the first time it happens in tract. I'm gonna leave the ones in tests for now, and will reassess if it happens again.

**Comment by SludgePhD** [comment]
Right, in tests this is not a big issue. Thanks for the quick fix!
