### ISSUE TITLE
 Error While Converting TFLite Model to Runnable State

### ISSUE THREAD

**Issue by mtobin-tdab** [sonos/tract#1411]
I am encountering an error while trying to convert a TFLite model using the `tract-tflite` crate. Unfortunately, I am unable to attach the model here, but may be able to provide a dummy version if required.

```rust
let model = tract_tflite::tflite()
    .model_for_path(model_path).map_err(|e| e.to_string())?
    .into_optimized().map_err(|e| e.to_string())?
    .into_runnable().map_err(|e| e.to_string())?;
```

The error occurs in `model_for_read` (line 34 of `tract/core/src/framework.rs`), specifically during the following loop (line 96 of `tract/tflite/src/model.rs`):

```rust
        for op in main.operators().context("No operators in Tflite model")? {
            for input in op.inputs().context("No input in Tflite  operator")? {
                if let Entry::Vacant(slot) = mapping.entry(input) {
                    let (fact, name) = flat_tensor_to_tract_fact(&root, main, input)?;
                    let value = fact.konst.with_context(|| format!("Error in TF file for operator {:?}. No prior computation nor constant for input {}", op, input))?;
                    let konst = target.add_const(name, value)?;
                    slot.insert(konst);
                }
            }
            self.0
                .deser_op(&root, main, &op, &mut target, &mut mapping)
                .with_context(|| format!("Parsing op {op:#?}"))?;
        }
```

**Error**
```
[src/lib.rs:267:13] &result = Err(
    "Translating proto model to model",
)
```

If you need the TFLite model for further investigation, please contact me, and I will try to provide a dummy version but since I don't know what the issue is, I am not sure how to recreate a model with the same behaviour (other models work fine)

**Environment:**

Rust version: `rustc 1.77.0-nightly (7ffc697ce 2024-01-24)`
Cargo version: `cargo 1.77.0-nightly (7bb7b5395 2024-01-20)`
Tract version: `tract-tflite 0.21.5`
Operating System: WSL `Ubuntu 22.04.4 LTS`
Thank you for your assistance.

**Comment by kali** [comment]
Can you reproduce by loading the model on the command line ? `tract model.tflite` should do the trick.

Alternatively, can you try to print more error context (the map_err(|e| e.to_string()) only display one level of the error stack).

In any case, I will very probably need a dummy model to reproduce and fix on my side.

**Comment by mtobin-tdab** [comment]
Thanks for the reply.

Output of `tract model.tflite`

```
[2024-05-21T17:09:55.420710967Z ERROR tract] Parsing op Operator {
        opcode_index: 7,
        inputs: Some(
            [
                229,
            ],
        ),
        outputs: Some(
            [
                230,
            ],
        ),
        builtin_options_type: NONE,
        builtin_options: None,
        custom_options: None,
        custom_options_format: FLEXBUFFERS,
        mutating_variable_inputs: None,
        intermediates: None,
    }
    
    Caused by:
        Unsupported: OperatorCode {
            deprecated_builtin_code: 14,
            custom_code: None,
            version: 1,
            builtin_code: LOGISTIC,
        }, inputs: [
            1,7,F32,
        ]
```

These are the operators used by my model:
```
{'MEAN', 'DEPTHWISE_CONV_2D', 'ADD', 'RELU', 'MAX_POOL_2D', 'LOGISTIC', 'CONV_2D', 'FULLY_CONNECTED'}
```
I can see now in the README that `LOGISTIC` is not supported.

Do you know if there is any plan to add support for this operator?

**Comment by mtobin-tdab** [comment]
Having had a further look I'm not able to find docs for the Logistic operator anywhere. I am wondering if it is an alias for `SIGMOID`?

**Comment by kali** [comment]
I'm pretty sure it is Sigmoid. I'm trying a binding from the tflite LOGISTIC to tract Sigmoid as we speak.

**Comment by kali** [comment]
Give a shot to the attach branch, tell me how it goes.

**Comment by mtobin-tdab** [comment]
Working with that branch! Thanks a lot for your help.
