### ISSUE TITLE
Different performance in applying tract as a Rust crate or Python API

### ISSUE THREAD

**Issue by banitalebi** [sonos/tract#1524]
Different performance in applying ```tract``` as a Rust crate and a ```trait``` as a Python API. Using the same test [dataset](https://drive.google.com/file/d/1sDwIpnQJD8iaRm8M322pITrD0esdMZZ6/view?usp=sharing) and the same [MobileNetV3.onnx](https://github.com/banitalebi/MobileNetV3-Inference/blob/main/mobilenetv3_model.onnx) file, the performance of inference using both scenarios is tested and reported in these [repositories](https://github.com/banitalebi/MobileNetV3-Inference). Based on the [results](https://github.com/banitalebi/MobileNetV3-Violence-Detection), each test scenario yields different outcomes. The python tract library is used for inference and accuracy is 82.78% while in the rust side accuracy is 77.28%.

**Comment by kali** [comment]
We can't track a bug statistically. The way to move this forward is to pick one specific input example, run it in the reference implementation and exporting input and output of the exact couterpart of tract in the reference implementation (input between pre-processing and NN model, output between NN model and post-processing). Then we can check how tract disagrees with the npz.

Look at https://github.com/sonos/tract/blob/main/doc/cli-recipe.md#running-a-test-case for how the npz should be generated (be careful about tensor matchine the node names and using the right item type).

**Comment by kali** [comment]
Before going through these loops, you may want to check your preprocessing. Some image network depends on an extra normalisation step on the input which is sometimes collapsed in the network, sometimes not (then is done as preprocessing). It may be enough to generate this kind of result drift.

**Comment by banitalebi** [comment]
Thank you, Kali, for your [comment](https://github.com/sonos/tract/issues/1524#issuecomment-2336120845). I reviewed the entire process again and found that the difference in the results is due to slight variations in how images are handled in the Python OpenCV library and the Rust image crate, as well as a bug in the previous version of the [MobileNetV3-Inference](https://github.com/banitalebi/MobileNetV3-Inference), which has now been fixed.

**Comment by kali** [comment]
Preprocessing can be deceivingly tricky... and my experience with NN is that when NN model inference breaks, it is usually not subtle.

Glad you could finally make it work.
