### ISSUE TITLE
Simple NN Model - fails to analyze MatMul

### ISSUE THREAD

**Issue by chenneking** [sonos/tract#1581]
Hi, using tract 0.21.7, I can't seem to load in the attached model. I would love to know if this behavior is expected. Model was defined and trained using PyTorch and exported using torch.onnx.export with opset_version 10.

`tract model.onnx` yields the following:

output:
`
[2024-11-26T00:03:42.549127000Z ERROR tract] Error at stage "type"

    Caused by:
        0: Translating node #3 "/linear1/MatMul" MatMulInference ToTypedTranslator
        1: Output mismatch after rewiring expansion for output #0: expected 14,F32 got 1,14,F32
`
model:
[model.onnx.zip](https://github.com/user-attachments/files/17910329/model.onnx.zip)

**Comment by mathieupoumeyrolsonos** [comment]
Thanks for the report. I think the linked PR is a fix.
