### ISSUE TITLE
SONOS aquirement of snips

### ISSUE THREAD

**Issue by CharlieBickerton** [sonos/tract#208]
Hi @kali, will the SONOS aquirement of snips affect this repo? https://forum.snips.ai/t/important-message-regarding-the-snips-console/4145

It would be such a shame!!

**Comment by kali** [comment]
Hey @CharlieBickerton, 

tract will soon be moved to Sonos public account, but development will be ongoing under the same licensing terms for the foreseeable future.

**Comment by CharlieBickerton** [comment]
Wonderful news @kali !! :) Please let me know if anything changes.
