### ISSUE TITLE
Cannot run object detection model from tf model zoo

### ISSUE THREAD

**Issue by oleid** [sonos/tract#255]
Dear all,

thanks a lot for this very interesting crate! I could run mobinet just fine.  [Faster RCNN Inception+ResnetV2](http://download.tensorflow.org/models/object_detection/faster_rcnn_inception_resnet_v2_atrous_coco_2018_01_28.tar.gz) seems not to work, though. 

It would seems bool support is missing. I got a crash due to unimplemented type 10, however this alone seems not to help:

```diff
diff --git a/tensorflow/src/tensor.rs b/tensorflow/src/tensor.rs
index 17cba22c..9dc3ae91 100644
--- a/tensorflow/src/tensor.rs
+++ b/tensorflow/src/tensor.rs
@@ -102,6 +102,7 @@ impl<'a> TryFrom<&'a TensorProto> for Tensor {
                         t.string_val.iter().map(|s| Blob(s.to_owned())).collect::<Vec<Blob>>();
                     tensor_from_repeated_field(&*dims, strings)?
                 }
+                DataType::DtBool => tensor_from_repeated_field(&*dims, t.bool_val.to_vec())?,
                 _ => unimplemented!("missing type (for _val()) {:?}", t.dtype),
             }
         };
```
Next crash isn't obvious at all to me:

```
thread 'main' panicked at 'explicit panic', tensorflow/src/model.rs:171:21
stack backtrace:
 [...]
  11: std::panicking::begin_panic
             at /home/oleid/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libstd/panicking.rs:438
  12: <tract_tensorflow::model::Tensorflow as tract_hir::framework::Framework<tract_tensorflow::tfpb::tensorflow::GraphDef>>::model_for_proto_model
             at tensorflow/src/model.rs:171
  13: tract_hir::framework::Framework::model_for_read
             at /home/oleid/src/tract/hir/src/framework.rs:32
  14: tract_hir::framework::Framework::model_for_path
             at /home/oleid/src/tract/hir/src/framework.rs:39
  15: example_tensorflow_mobilenet_v2::main
```

EDIT:

Crash as `i` starts with `^`:
 ```
[tensorflow/src/model.rs:171] i = "^Preprocessor/map/while/Identity"
```

Maybe you have an idea?

**Comment by kali** [comment]
Hey, thanks for your interest in tract !

I'll need to have a look at the model. 

What is happening here is... tensorflow is a complex beast with many many many semi-redundant features. The ^ thing denotes a control input for a node. This means that the downstream node requires the upstream node to have run before being executed. I prefer not to have this feature in the core of tract, as I am trying to keep it as simple as possible. There are other networks that I'm currently working on (recurring nets) that also make use of this feature, and I am currently mapping some of these usages to the core concepts I actually want tract to know about. As soon as these network will work, I will have a look at this one and see if I can make it run too.

**Comment by kali** [comment]
Holy cow, that beast has 18245 nodes! OK, don't hold your breath. This network is really big, and really complicated. Many features will be missing. It may work one day, but it won't happen overnight.

**Comment by kali** [comment]
Yeah. Rule of thumb for tract: ONNX works better. There is about 85% coverage. Some parts are missing, some are relatively easy to add (simple non-performance critical missing ops) some are way harder (tensors with dynamic size, tensor sequences).

And if tract does not support something as ONNX, it is likely not supported for TF either.

But tell me how it goes. if you find models that work, I'll be happy to know. If you find some that do not work, I'll try to assess what is missing.
