### ISSUE TITLE
Optimise nets with symbolic dimension(s)

### ISSUE THREAD

**Issue by kali** [sonos/tract#313]
This is a followup to #300 . This issue is an epic, not 100% sure how everything will go. There may be valuable incremental improvements too here and there.

* To what extent can we optimize a network retaining the symbolic stream dimension, so each Plan::run can run with a different dimension ? (required for a full fix to #300)
* Can we generalize to get optimized support for
   * other dimensions (batch, aka N dim ?) (somewhat hinted at by #300)
   * dynamically shaped tensors (required by some onnx ops)

**Comment by joverwey** [comment]
Does this mean that tract does not support tensors where one dimension is unknown?

The input to my model is a tokenized string converted to hashes.

```
let input: Vec<u64>

let model = 
    onnx()
            .model_for_path(model_path)?
            .with_input_fact(0, <PARTIAL_SHAPE?>)?
```

Is it possible to create a SimplePlan for these kinds of inputs?

**Comment by kali** [comment]
Yes, and no. Check out the conversation in #300 to see how to deal with that in the current situation: 
1/ doing the expensive decluttering with the partial shape and keep the obtained network permanently,
2/ for each input, concretize the missing dim, optimize and run.

It is not nice, but it should work and improve a lot the performance already. I think the long term fix for this issue is going to happen, but it will take a while.

**Comment by joverwey** [comment]
Thanks, I tried this but I am getting an error:

```
Error: ONNX(TractError(Msg("Failed analyse for node #61 "61" ConstantOfShape"), State { next_error: Some(TractError(Msg("Eager eval"), State { next_error: Some(TractError(Msg("Casting 2xTDim 1, S to I32"), State { next_error: Some(TractError(Msg("Unresolved value 'S'"), State { next_error: None, backtrace: InternalBacktrace { backtrace: Some(   0: backtrace::backtrace::dbghelp::trace
```

My model is slightly different in that I have 2 inputs, both of the same variable length.
```
        let model: ModelImpl<_, _> = onnx()
            .model_for_path(model_path)?
            .with_input_fact(0, InferenceFact::dt_shape(i64::datum_type(), tvec!(1.into(), TDim::s())))?
            .with_input_fact(1, InferenceFact::dt_shape(f32::datum_type(), tvec!(1.into(), TDim::s())))?
            .into_typed()?
            .declutter()?;

```

The second input is a mask on the first input.
When evaluating I do:

```
        let tokens_tensor: Tensor = Array::from_shape_vec((1, storage.tokens.len()), storage.tokens.clone())?.into();
        let mask_tensor = tract_ndarray::Array2::<f32>::ones((1, storage.tokens.len())).into();
        let output_tensors =
            &model
                .concretize_stream_dim(storage.tokens.len())?
                .optimize()?
                .into_runnable()?
                .run(tvec![tokens_tensor, mask_tensor])?;
```

Will concretize_stream_dim apply to both inputs with variable length?

I'm trying to run a BERT model. Have you tried this with Tract? 

Thanks
Johan

**Comment by kali** [comment]
Mmm... could you give me a model, so I can have a look ? BERT models are on my roadmap somewhere, so I'm interested in at least figuring out what is wrong. (Model does not have to be trained...)

I did not expect trouble to come from ConstantOfShape, but it's true the current implementation expects known integer sizes, not symbolic ones. I thought it would be enough, but it looks like I was wrong :)

And yes, concretize will substitute the S var with the same value in both inputs.

https://send.firefox.com can work for big files.

**Comment by joverwey** [comment]
This BERT model is similar to mine:

https://github.com/onnx/models/tree/master/text/machine_comprehension/bert-squad

If you can get this one to run, we should be in good shape.

**Comment by kali** [comment]
@joverwey created a separate issue for the specific BERT problems. Let's try to leave that one focused on the symbolic dimension optimisation issue.

**Comment by bminixhofer** [comment]
Hi, I'll give implementing symbolic dimensions / concretization in tractjs a shot. Just to make sure I understand the current state of this issue correctly:

At the moment, the API supports multiple symbolic dimensions (via the Symbol API and `concretize_stream_dims` since 0.11), but more than one symbolic dimension can not be concretized yet. 

Is that correct? Thanks.

**Comment by kali** [comment]
I think it may also work with multiple symbols actually :) Never tried though.

**Comment by bminixhofer** [comment]
Oh, I just tried adapting the snippet you sent yesterday to also have the batch size as streaming dim:

```rust
use tract_core::dim::{Symbol, ToDim};
use tract_onnx::prelude::*;

fn main() -> TractResult<()> {
    let model = tract_onnx::onnx()
        .model_for_path("model.onnx")?
        .with_input_fact(
            0,
            InferenceFact::dt_shape(
                u8::datum_type(),
                tvec!(TDim::from('b'), TDim::from('s') * 2),
            ),
        )?
        .into_optimized()?;

    let optimized_model = model
        .concretize_dims(
            &SymbolValues::default()
                .with('s'.into(), 20)
                .with('b'.into(), 1),
        )?
        .optimize()?
        .into_runnable()?;

    let input: Tensor = tract_ndarray::Array2::<u8>::zeros((1, 40)).into();
    println!("{:#?}", optimized_model.run(tvec!(input))?);

    Ok(())
}
```

And I get:

```
    Finished release [optimized] target(s) in 1.75s
     Running `target/release/tractdyn`
thread 'main' panicked at 'Can not work out a data format with two actual symbolic dim', /home/bminixhofer/.cargo/registry/src/github.com-1ecc6299db9ec823/tract-core-0.11.1/src/ops/nn/data_formats.rs:33:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

So it looks like it does not work yet (with this model).

**Comment by kali** [comment]
Also to clarify: I consider the concretize_dims a semi-hack waiting for this issue to be resolved fully: I want to us to be able to call into_optimized() with one or multiple symbolic dimensions, and get a RunnableModel that will accept tensor of any size consistent with the symbols, and be reasonably efficient.

**Comment by bminixhofer** [comment]
Good to know, that sounds great.
 I'll think a bit about how this could look when calling from JS (keeping it pretty constrained / opinionated for now, until this is resolved), I'll ping you in the tractjs Repo once there's a PR if you want to take a look at the JS API :)

**Comment by kali** [comment]
I will close this issue, as whatever it was tracking is implemented now. Feel free to open issue for remaining problems.
