### ISSUE TITLE
NonZero ONNX operator support

### ISSUE THREAD

**Issue by joverwey** [sonos/tract#343]
It looks like this operator is not supported yet.  This seems to be the one missing operator used by my model. Would this be hard to add?

**Comment by kali** [comment]
NonZero output shape can not be determined from the input shape, it depends on the actual content of the input tensor, breaking one of the core assumptions of tract optimization. This is a recently recurring occurrence with BERT and other modern networks, so I will work on relaxing this constraint (see #313) but it will take some time (months).

In the meantime, I could make a NonZero network, but you would not be able to optimize the network, and performance would be abysmal (for the entire network, not only the operator). Would it still help ?

**Comment by joverwey** [comment]
Yes, that would still be helpful. Right now for the BERT model this is the thing that prevents me from running it at all. The idea is to compile everything down to web assembly to run on the client. Even if the inference is slower, it may still be faster than making an http call.

**Comment by kali** [comment]
link #331
