### ISSUE TITLE
TensorListReserve Operation

### ISSUE THREAD

**Issue by bio43** [sonos/tract#370]
Hi there,

When I try to run a frozen TensorFlow graph with the TensorListReserve operation Tract throws an error (it seems that the implementation is missing). How feasible would it be to add this instruction?

Thanks!

**Comment by kali** [comment]
Hello !

tract does not have support for TensorFlow's TensorList, (or their Sequence avatar in ONNX). Adding this is a big change, as it implies to change the basic exchange format in the network from a tensor to either a tensor or a TensorList (or do something clever with dimension and indices). It's not on the roadmap right now.

Out of curiosity, can you tell us what application domain or model family you're using that requires them ?

**Comment by bio43** [comment]
Hi @kali , it's a simple LSTM in TensorFlow:

```
import tensorflow as tf

def build_model(vocab_size, embedding_dim, rnn_units, batch_size):
  model = tf.keras.Sequential([
    tf.keras.layers.Embedding(vocab_size, embedding_dim,
                              batch_input_shape=[batch_size, embedding_dim]),
    tf.keras.layers.LSTM(rnn_units),
  ])
  return model

embedding_dim = 100
units = 256
vocab_size = 300
batch_size = 32

model = build_model(vocab_size, embedding_dim, units, batch_size)
model.compile(optimizer='adam', loss='sparse_categorical_crossentropy')
```

It gives the attached frozen graph. 
[model (3).pb.zip](https://github.com/sonos/tract/files/5353825/model.3.pb.zip)

Any idea how I can work around it? Not using LSTMs is probably not a solution :-)

**Comment by kali** [comment]
Tensorlist for lstm ? seriously ? Wow... kids, this is why, when you're just one person, you should not try keeping up with a team with virtually unlimited resources :)

I'll have a look at your model, but anything will take a lot of time. My suggestion for a quick workaround would be to use pytorch and onnx. tract has first grade support for ONNX LSTM and Scan operators (allowing to redefine the LSTM any way you want).

Tensorflow 1 LSTM models may also work, but no warranties here, matching TF flow model with tract has proven difficult, TF semantics are actually quite complex for recurring networks, with little documentation, and no reusable test suite...

You can also try converting keras to ONNX (the blog post you linked explains how). Depending on how they do it (whether they use or not the ONNX TensorSequences, basically) you may get lucky.

**Comment by kali** [comment]
Closing. TensorList and Sequense are not on the roadmap.
