### ISSUE TITLE
Reshape with streaming dimension

### ISSUE THREAD

**Issue by bminixhofer** [sonos/tract#374]
Hi! I've been improving the model architecture in [nnsplit](https://github.com/bminixhofer/nnsplit/) (which now uses tract as backend for Rust and Javascript by the way!) and came across a problem. I'm doing downsampling, then feed the data through an LSTM, then upsampling: https://github.com/bminixhofer/nnsplit/blob/758bef036c4f6d57b61f99e2a88b2503cb8d5e4f/train/model.py#L41-L52

so I need to reshape the data according to the input dimension. [Here is one such ONNX model](https://github.com/bminixhofer/nnsplit/blob/master/models/fr/model.onnx).

And here's simplified code:

`Cargo.toml`
```toml
[package]
name = "sblstmtest"
version = "0.1.0"
authors = ["Benjamin Minixhofer <bminixhofer@gmail.com>"]
edition = "2018"

[dependencies]
tract-onnx = "0.11.0"
tract-core = "0.11.0"
```

`src/main.rs`
```rust
use tract_core::dim::{Symbol, ToDim};
use tract_onnx::prelude::*;

fn main() -> TractResult<()> {
    let model = tract_onnx::onnx()
        .model_for_path("model.onnx")?
        .with_input_fact(
            0,
            InferenceFact::dt_shape(u8::datum_type(), tvec!(1.to_dim(), Symbol::new('s').into())),
        )?
        .into_optimized()?;

    let optimized_model = model
        .concretize_dims(&SymbolValues::default().with(Symbol::new('s'), 40))?
        .optimize()?
        .into_runnable()?;

    let input: Tensor = tract_ndarray::Array2::<u8>::zeros((1, 40)).into();
    println!("{:#?}", optimized_model.run(tvec!(input))?);

    Ok(())
}
```

```
(base) ➜  ~/Documents/Experiments/sblstmtest git:(master) ✗ cargo run --release 
    Finished release [optimized] target(s) in 0.10s
     Running `target/release/sblstmtest`
Error: TractError(Msg("Failed analyse for node #69 \"Reshape_46\" Reshape"), State { next_error: Some(TractError(Msg("Infering facts"), State { next_error: Some(TractError(Msg("Applying rule Given2Rule { (inputs[0].shape, inputs[1]) }: Invalid"), State { next_error: None, backtrace: InternalBacktrace { backtrace: None } })), backtrace: InternalBacktrace { backtrace: None } })), backtrace: InternalBacktrace { backtrace: None } })
```

this looks to me like reshape has a problem if the size to reshape to is not fully determined?

Another thing I noticed, with this code (only loading, no stream dim):

```rust
use tract_core::dim::ToDim;
use tract_onnx::prelude::*;

fn main() -> TractResult<()> {
    let _model = tract_onnx::onnx()
        .model_for_path("model.onnx")?
        .with_input_fact(
            0,
            InferenceFact::dt_shape(u8::datum_type(), tvec!(1.to_dim(), 10.into())),
        )?
        .into_optimized()?;

    Ok(())
}
```

`cargo run` takes > 5 minutes on my laptop while `cargo run --release` takes a couple of seconds since v0.11. Let me know if I should open a separate issue for that.

```
(base) ➜  ~/Documents/Experiments/sblstmtest git:(master) ✗ time cargo run
   Compiling sblstmtest v0.1.0 (/Users/bminixhofer/Documents/Experiments/sblstmtest)
    Finished dev [unoptimized + debuginfo] target(s) in 4.34s
     Running `target/debug/sblstmtest`
cargo run  359.79s user 1.46s system 99% cpu 6:02.23 total
(base) ➜  ~/Documents/Experiments/sblstmtest git:(master) ✗ time cargo run --release
   Compiling sblstmtest v0.1.0 (/Users/bminixhofer/Documents/Experiments/sblstmtest)
    Finished release [optimized] target(s) in 1.21s
     Running `target/release/sblstmtest`
cargo run --release  3.19s user 0.20s system 248% cpu 1.364 total
```

**Comment by kali** [comment]
1/ Reshape is actually quite complex, and the symbolic dimensions do not help. In this particular case, tract is asked to reshape a tensor of shape 1,S/2,4 to (-1),S,2 . (-1 means "compute the missing dimension so that it makes sense", and the slash sign is integer division, there is a convolution of stride 2 at the beginning of the net.)
It looks quite alright, but looking closely, it only works if S is even (try to substitute S<-3). Let me think a bit about how to deal with this :)
2/ do you mean that the decluttering of this net is slower than it use to be ? It may very well be, i will need to track this metrics somehow... I can have a look.

**Comment by bminixhofer** [comment]
Regarding 1.) Thanks! It's a bit unusual I guess, I downsample the input so that the LSTM has to do less work. I externally make sure that the input length is always divisible by 2.

Regarding 2.): not necessarily decluttering. The code from above (just model loading!):

```rust
use tract_core::dim::ToDim;
use tract_onnx::prelude::*;

fn main() -> TractResult<()> {
    let _model = tract_onnx::onnx()
        .model_for_path("model.onnx")?
        .with_input_fact(
            0,
            InferenceFact::dt_shape(u8::datum_type(), tvec!(1.to_dim(), 10.into())),
        )?
        .into_optimized()?;

    Ok(())
}
```

takes 5 minutes on my laptop since v0.11 when running without the `--release` flag. Before that it took only a couple of seconds, so a huge performance regression happened. But it's fine when running with `--release`.

**Comment by kali** [comment]
1/ We have models where we downsample before the LSTM, but we don't have Reshape in them. One way could be to allow inputs to use shapes like 1,2s. I'll be pondering this.
2/ Mmm... this code actually does decluttering as part of into_optimized(). I noticed that debug builds where slower than they used to be, but that's not something I track. But it's now a bit inpractical. Let's make it a separate issue.

**Comment by bminixhofer** [comment]
One way I wouldn't need the Reshape is by supporting Deconvolution, but I'm not sure if that's easier / if this issue might be relevant to other networks you want to support as well.

**Comment by kali** [comment]
I would like to support Deconvolution, not having it is getting problematic in more and more situations as time goes by, so this is probably going to happen. That said I'm going to give a shot a making Reshape work with something like "2S", as this is linked to the generalization of the symbolic dimensions.

**Comment by kali** [comment]
Here we go. Got it to work like that (against the branch #375).

```rust
use tract_core::dim::{Symbol, ToDim};
use tract_onnx::prelude::*;

fn main() -> TractResult<()> {
    let model = tract_onnx::onnx()
        .model_for_path("model.onnx")?
        .with_input_fact(
            0,
            InferenceFact::dt_shape(u8::datum_type(), tvec!(1.to_dim(), TDim::from('s') * 2)),
        )?
        .into_optimized()?;

    let optimized_model = model
        .concretize_dims(&SymbolValues::default().with('s'.into(), 20))?
        .optimize()?
        .into_runnable()?;

    let input: Tensor = tract_ndarray::Array2::<u8>::zeros((1, 40)).into();
    println!("{:#?}", optimized_model.run(tvec!(input))?);

    Ok(())
}
```

A few note: be careful not to use `Symbol::new`, because it creates a new symbol each time, regardless of the character you provides. I have added a `Symbol::from(char)` that acts more like you were expecting (retrieve or else create).

**Comment by bminixhofer** [comment]
Thanks for the quick fix! I can confirm this works now.
