### ISSUE TITLE
Unsupported combination for MatMul codegen

### ISSUE THREAD

**Issue by acrrd** [sonos/tract#399]
I have this error:
`Unsupported combination for MatMul codegen (a: I8, b:U8, q: Some(QParams { c_datum_type: I32, zero_point_a: None, zero_point_b: None, zero_point_c: None, scale_factor: None, inputs_kind: Some([ZeroPointA(2)]) }))
`

**Comment by acrrd** [comment]
In PR #400 I add this version of the multiplication for the generic algorithm. Would be difficult to add the respective optimized version? I do not have experience with assembly so I do not even know if it is possible.

**Comment by kali** [comment]
link #413
