### ISSUE TITLE
TFLite support / example

### ISSUE THREAD

**Issue by apenugon** [sonos/tract#437]
Hi, apologies if this is already documented somewhere - I saw tensorflow lite is mentioned in the readme, but the process to actually load a tflite model seems unclear. I tried to use the tract-tensorflow crate to load one, but that did not work. Any idea what the actual method is?

**Comment by kali** [comment]
Hey ! Thanks for your interest in tract.

TFlite format is not supported. It is mentioned in the readme as tract lives in the same ecosystem, but not specific efforts has been made to support it. It would make sense to support TFlite, actually. The architecture already supports at least partially 4 formats, and TFLite is a relatively small operator set (compared to TF baroque nightmare). But is at a lowest possible priority for us.

I can't say for sure without getting more specific information, but the safest route to get a model to run in tract is ONNX. It is a relatively comprehensive operator set, I would guess anything that you can do in TFLite can be encoded in ONNX, and support for it in tract is relatively good, despite a few niche operators missing.

Happy to help you navigate this if you want to provide us a bit more specific information.

Hope this helps, and I will keep your remarks in mind next time I'm doing a README update.

**Comment by apenugon** [comment]
Ahh, that makes sense. I was hoping the tflite format could help me squeeze out a bit faster inference time since the onnx version of the model takes a while at first inference. Will keep investigating. Thank you!

**Comment by kali** [comment]
In that case, maybe you can translate from onnx to nnef once, then load from nnef. It should be faster than loading from onnx (see https://github.com/sonos/tract/tree/main/examples/nnef-dump-mobilenet-v2)

**Comment by apenugon** [comment]
Thanks! I'm going through that process now, but my model uses Resize ops which don't seem supported for tract/nnef yet. I know ConvTranspose isn't supported - do you know if any other similar ops are supported?

**Comment by kali** [comment]
Resize has a tiny bit of support in tract-core, very partial, and is not mapped at all to nnef. So if you're lucky enough for it to work with onnx, going through nnef will certainly break it.
ConvTranspose is it's the way.

**Comment by apenugon** [comment]
Got it! will be looking forward to that.
