### ISSUE TITLE
Apple M1 vs x86

### ISSUE THREAD

**Issue by CharlieBickerton** [sonos/tract#439]
Hi guys (@kali ),

We've just got a mac mini with the new m1 chip, it's producing different results on our deployed model at inference compared to x86. 

We think this is also the reason behind a bug we have, which results in different results for inference on mobiles compared to inference on the same data on our server.   

Do you have any idea about what might be going on? 

Thanks!

**Comment by kali** [comment]
There is a bug I'm struggling with on aarch64, but as far as I can tell, it only impacts quantized models, and the impact is quite marginal (it's a rounding algorithm difference).

Except for this case, all of my "canary" models are working as expected on M1. So i'm curious to know more :)

**Comment by CharlieBickerton** [comment]
The impact is seems quite marginal for us as well. We use a frozen TF2 CNN for detecting activity on IMUs - our activity detection is happening at different times on M1 to x64. 

We use activity detection as piece in our puzzle to calculate metrics about the activity. Whilst it seems to be marginal during use i.e. the activity is detected with low latency, when our sessions are reprocessed on it can the metrics quite a lot.

**Comment by kali** [comment]
There can be some small differences in float models too, actually... floats are a semi broken approximation of real numbers, after all. Addition is not strictly commutative, and tract is likely to reorder additions in matrix multiplications (including convolutions). I'm surprised it is noticeable though... this is suspect.

Any change you can share a model and an input that produce different results so I can have a closer look ?

**Comment by CharlieBickerton** [comment]
Sure, we'll get this over to you tomorrow. 

Thanks for the fast response and for looking into it!

**Comment by kali** [comment]
Please use mathieu <dot> poumeyrol <at> sonos <dot> com.

**Comment by pruthvikar** [comment]
Hey @kali , I work with @CharlieBickerton.

I may have jumped the gun on this issue. Taking a closer look, it seems like the cause is because of asin producing different results which are then fed into the model.

I'lll keep you posted as I confirm this.

**Comment by pruthvikar** [comment]
It looks like the models also produce different results, but the values look like they could be off by a rounding error.  Here's an example of two different outputs given the same input 

1. `0.038813025`
2. `0.038813036`

We're also very getting very slight differences in the outputs for `asin`. It seems like these are just down to platform differences which we can remedy by setting a precision.

**Comment by kali** [comment]
Yes... tract does not commit to giving the same results on all architectures beyond rounding errors which are tolerable for neural net applications. In tests, I typically use `Tensor::close_enough(true)` to check for equality. It basically allow for some relative and absolute errors, in the order of 5e-5, iirc.

So this stays in the range of expected behaviour.

**Comment by pruthvikar** [comment]
Good to know and thanks for your help!
