### ISSUE TITLE
Wrong input number. Rules expect 4, node has 3.

### ISSUE THREAD

**Issue by mocsy** [sonos/tract#449]
I'm experimenting with a different mobilenet-v2 model than the one in the example.
I changed three lines only, and added `with_input_names`.
However I get errors and I don't see what else I miss, any help is appreciated.

```rust
    let model = tract_tensorflow::tensorflow()
        // load the model
//--.model_for_path("mobilenet_v2_1.4_224_frozen.pb")?
        .model_for_path("frozen_inference_graph_pascal.pb")?
        // specify input type and shape
        .with_input_fact(0, InferenceFact::dt_shape(u8::datum_type(), tvec!(1, 224, 224, 3)))?
//--.with_input_fact(0, InferenceFact::dt_shape(f32::datum_type(), tvec!(1, 224, 224, 3)))?
        .with_input_names(&["ImageTensor"])?
        // optimize the model
        .into_optimized()?
        // make the model runnable and fix its inputs and outputs
        .into_runnable()?;

    // open image, resize it and make a Tensor out of it
//--let image = image::open("grace_hopper.jpg").unwrap().to_rgb8();
    let image = image::open("image1.jpg").unwrap().to_rgb8();
    let resized =
        image::imageops::resize(&image, 224, 224, ::image::imageops::FilterType::Triangle);
    let image: Tensor = tract_ndarray::Array4::from_shape_fn((1, 224, 224, 3), |(_, y, x, c)| {
        resized[(x as _, y as _)][c] as f32 / 255.0
    })
    .into();

    // run the model on the input
    let result = model.run(tvec!(image))?;

    // find and display the max value with its index
    let best = result[0]
        .to_array_view::<f32>()?
        .iter()
        .cloned()
        .zip(1..)
        .max_by(|a, b| a.0.partial_cmp(&b.0).unwrap());
    println!("result: {:?}", best);
    Ok(())
```

```bash
$ cargo run
   Compiling example-tensorflow-mobilenet-v2 v0.1.0 (/mnt/linux_storage/ext/tract/examples/tensorflow-mobilenet-v2)
    Finished dev [unoptimized + debuginfo] target(s) in 2.62s
     Running `/mnt/linux_storage/ext/tract/target/debug/example-tensorflow-mobilenet-v2`
Error: Failed analyse for node #88 "stack_3" Pack

Caused by:
    0: Infering facts
    1: Wrong input number. Rules expect 4, node has 3.
```

Pack is listed as implemented and testes, so it's likely not that (https://github.com/sonos/tract#tensorflow).

The example model has `(name=input, type=float(1), shape=None)` and the one I'm trying to start  has `(name=ImageTensor, type=uint8(4), shape=[1,?,?,3])`.

Based on that I think that the difference from the example model is the input name (hence `.with_input_names(&["ImageTensor"])`) and type (`hence u8::datum_type()`).

```bash
$ bazel-bin/tensorflow/tools/graph_transforms/summarize_graph --in_graph=mobilenet_v2_1.4_224_frozen.pb
Found 1 possible inputs: (name=input, type=float(1), shape=None) 
No variables spotted.
Found 1 possible outputs: (name=MobilenetV2/Predictions/Reshape_1, op=Reshape) 
Found 6116699 (6.12M) const parameters, 0 (0) variable parameters, and 0 control_edges
Op types used: 158 Const, 36 BiasAdd, 36 Conv2D, 35 Relu6, 17 DepthwiseConv2dNative, 17 FusedBatchNorm, 10 Add, 2 Reshape, 1 AvgPool, 1 Placeholder, 1 Shape, 1 Softmax, 1 Squeeze
To use with tensorflow/tools/benchmark:benchmark_model try these arguments:
bazel run tensorflow/tools/benchmark:benchmark_model -- --graph=/mnt/linux_storage/ext/tract/examples/tensorflow-mobilenet-v2/mobilenet_v2_1.4_224_frozen.pb --show_flops --input_layer=input --input_layer_type=float --input_layer_shape= --output_layer=MobilenetV2/Predictions/Reshape_1
```

The model's input layer is slightly different:
```bash
$ bazel-bin/tensorflow/tools/graph_transforms/summarize_graph --in_graph=frozen_inference_graph_pascal.pb 
Found 1 possible inputs: (name=ImageTensor, type=uint8(4), shape=[1,?,?,3]) 
No variables spotted.
Found 1 possible outputs: (name=SemanticPredictions, op=Slice) 
Found 2146839 (2.15M) const parameters, 0 (0) variable parameters, and 4 control_edges
Op types used: 374 Const, 357 Identity, 54 FusedBatchNorm, 38 Conv2D, 34 Relu6, 17 DepthwiseConv2dNative, 13 Add, 10 StridedSlice, 10 BatchToSpaceND, 10 SpaceToBatchND, 8 Sub, 5 Pack, 4 GreaterEqual, 4 Assert, 4 Shape, 4 ResizeBilinear, 3 Cast, 3 Relu, 2 ExpandDims, 2 Squeeze, 2 Maximum, 2 Mul, 1 Slice, 1 LogicalAnd, 1 Reshape, 1 Placeholder, 1 Pad, 1 Equal, 1 ConcatV2, 1 BiasAdd, 1 AvgPool, 1 ArgMax
To use with tensorflow/tools/benchmark:benchmark_model try these arguments:
bazel run tensorflow/tools/benchmark:benchmark_model -- --graph=/mnt/linux_storage/ext/tract/examples/tensorflow-mobilenet-v2/frozen_inference_graph_pascal.pb --show_flops --input_layer=ImageTensor --input_layer_type=uint8 --input_layer_shape=1,-1,-1,3 --output_layer=SemanticPredictions
```

**Comment by kali** [comment]
Hey, thanks for your interest in `tract` !

Support for TensorFlow is a long way for being complete, and it will probably never be, as TensorFlow is a way too big beast for our scarce resources. As a consequence, we implement features on a by need basis, weighting implementation complexity, and feature genericity with absolute subjectivity.

In your case, it looks like you've hit one of the limitation of our implemntation of the `Pack` operator. Pack is relatively simple, so fixing this is probably easy. Would you be able to share this net with so I can have a closer look ?

**Comment by mocsy** [comment]
Definitely. It's the [frozen](http://download.tensorflow.org/models/deeplabv3_mnv2_pascal_train_aug_2018_01_29.tar.gz) `mobilenetv2_coco_voc_trainaug` from the [deeplab zoo](https://github.com/tensorflow/models/blob/master/research/deeplab/g3doc/model_zoo.md) from the apache 2.0 [tf models](https://github.com/tensorflow/models) repo.

**Comment by kali** [comment]
Thanks ! I'm having a look at the network right now. There are a few operators missing indeed and a few weird stuff that need to be done.
* Pack: pack was fine but the parser was not dealing correctly with the non-data input from tensorflow which are usually ignored in tract. Should be fixed now.
* Assert: Mapped to NoOp. validating inputs is not tract job.
* ArgMax: weirdly this one never occured in tract test TF models. Expanded it to the one in hir.
* ResizeBilinear: From the look of it, the (incomplete) implementation or resize done for ONNX is good enough. Moving it to hir, and expanding TF op to it.

I'm in the middle of these fixes, will try to finish them ASAP, maybe tonight if ResizeBilinear cooperates.

Thanks for the remark about the README. ONNX (and NNEF) having better support, we should probably put these frameworks forward instead (and we already have working examples...)

**Comment by kali** [comment]
Closing, I think we got it working.
