### ISSUE TITLE
ONNX CumSum op

### ISSUE THREAD

**Issue by kali** [sonos/tract#472]

**Comment by dHumanities** [comment]
Same problem. Any solution?

**Comment by kali** [comment]
We haven't encoutered it in our application or in the wild yet, so it's low priority for us. I think it is relatively straightforward to implement, happy to help if you feel like giving it a shot.

**Comment by dHumanities** [comment]
I will give it a try but I am not familiar with Rust. So, can you help pointing out which files are related if I help to implement the CumSum op for Onnx?

**Comment by kali** [comment]
All right, if you don't have prior experience, it may be a bit of a tough one. Let me have a look if I can somehow derive it trivially from the Reduce operator before diving into.
