### ISSUE TITLE
Propagate error if onnx file is invalid

### ISSUE THREAD

**Issue by HalfVoxel** [sonos/tract#499]
When loading an onnx file, tract will panic if the proto does not contain a graph field. This is undesirable because it prevents us from doing proper error handling.
![image](https://user-images.githubusercontent.com/1144597/119791029-bbeabf00-bed4-11eb-91cd-0edfdd615756.png)

**Comment by kali** [comment]
Agreed, there is no good reason for this. Want to make a PR ?

**Comment by aron-granberg** [comment]
Done
