### ISSUE TITLE
UnimplementedOp: If 

### ISSUE THREAD

**Issue by gstvg** [sonos/tract#529]
Hi, I tried running https://github.com/snakers4/silero-vad ONNX model but it uses the If Op.
Does tract error returns all unimplemented ops encountered or only the first one?
If no, and "If" is the only unimplemented op, is it easy to implement? I know some ops looks easy to implement by name but in reality are very complicated.

Btw, they are currently looking for a way to easily run on edges devices https://github.com/snakers4/silero-vad/issues/37, a field where tract excels.

Thanks!

**Comment by kali** [comment]
Hey, I happen to have a partial "If" implementation in a work-in-progress branch (`play-with-spleeter`). 

"If" is a bit tricky as it is a control-flow operation, but if the use case is something like "if(training_mode)", then it should be easy enough. If it is more subtle, then I'll need to have a look.

if you want to get an idea of the problem you may encounter with a new model, a good starting point is to run `tract --pass load model.onnx`... Tract should dump the model as soon as it is loaded, and UnimplementedOp will appear relatively obviously.

Tell me what you find, and if it's easy enough, we'll make these models work :)

**Comment by kali** [comment]
I am actually having a look. I isolated the "If" operator introduction from the branch and I think I can get these models to work. Stay tuned.

**Comment by kali** [comment]
Hey @gstvg, I have merged basic support for "If" on the main branch. From what I'm seeing it should be enough to run these models. Tell me how it goes.
