### ISSUE TITLE
Npu support

### ISSUE THREAD

**Issue by markusgod** [sonos/tract#550]
Can tract take advantage of soc with npu coprocessor like [rk3399](https://www.rock-chips.com/a/en/products/RK33_Series/2018/0130/874.html)?

**Comment by kali** [comment]
No. While are watching the NPU space and experimenting internally with some NPUs, we are not supporting them at this stage.

Would you happen to know which NPU that rk3399 is using ? It looks like there is very little information available publicly.

**Comment by markusgod** [comment]
No, I don't know what npu they are using but it looks like it is their own npu.

https://github.com/radxa/rknn-api/blob/master/rknn-api/Rockchip_User_Guide_RKNN_API_V1.3.0_EN.pdf

**Comment by kali** [comment]
Thanks for sharing the documentation... but no, this is not on the roadmap.
