### ISSUE TITLE
Onnx Unimplemented: Range

### ISSUE THREAD

**Issue by Rikorose** [sonos/tract#558]
Hi there,

I think I am getting closer to getting my model running with tract :)

However, I am running into the following error message:
```
Error: Translating node #22 "Range_174" Unimplemented(Range) ToTypedTranslator
```
I am currently struggling to track down, which pytorch/python op is translating to this onnx operator. The onnx model is [here](https://github.com/sonos/tract/files/7354254/op.zip)

I see there is a tensorflow range implementation but no onnx, no?

**Comment by kali** [comment]
Yes, and we also have a PR somewhat cloning it to ONNX. I was not super happy with the code (mine, just from three years ago) that was cloned (or moved) and wanted to revisit it a bit. I will try to do that quickly, it's so much easier than the deconvolution stuff...

**Comment by kali** [comment]
please try PR #559 and let me know. Unfortunately, I could not guess the right input shapes for your model, so I'm not 100% sure.

**Comment by kali** [comment]
Great, tell me if I can help !
