### ISSUE TITLE
Support scikit-learn

### ISSUE THREAD

**Issue by rth** [sonos/tract#56]
I was wondering how much effort would be to support some of scikit-learn models. They can be exported to ONNX with https://github.com/onnx/onnxmltools

I imagine at least linear models shouldn't be too difficult.

Would that be in scope of this project?

**Comment by ogrisel** [comment]
Note that there is now a dedicated repo for scikit-learn exporters:

https://github.com/onnx/sklearn-onnx

As far as I know, onnxruntime it the only ONNX backend that can execute all scikit-learn models and pipelines exported via sklearn-onnx at this point.

**Comment by rth** [comment]
Yes, I realized I confused onnxmltools (that doesn't seem very production ready, no docs etc) with sklearn-onnx. The onnx docs are just not very consistent (e.g. [here](https://github.com/onnx/tutorials#getting-onnx-models)).

Anyway, I opened this issue mostly because I was interested in a lightweight inference library in Rust (even if it doesn't support all estimators).

**Comment by kali** [comment]
Hey forlks, thanks for your interest in tract !

I'm all for supporting more networks, more operators, more everything. One of the short/mid term goal is to pass 100% of the onnx backend testsuite. We are aware that the test suite do not cover the entire field (small types for instances are more or less absent), so your mileage may vary with exported networks.

As of today, flow-control and recurring operators are not implemented at all. We will make a push on the recurring ops in the woming weeks.

In the mean time, we would love to collect op-level or network-level tests cases complementing the coverage offered by the onnx repository. And we have not try anything with scikit, so if you want to experiment a bit and collect the results, yeah, we are very curious and we will try to fix whatever needs fixing.

**Comment by kali** [comment]
Closing in favor of operator-per-operator issues.
