### ISSUE TITLE
UnimplementedOp: ArrayFeatureExtractor

### ISSUE THREAD

**Issue by aeveris** [sonos/tract#571]
I tried running a classifier trained with scikit-learn and exported as ONNX, which seems to use the `ArrayFeatureExtractor` Op.
Are there plans to implement this Op? If not, is there an estimate on how difficult it would be to implement this?

**Comment by aeveris** [comment]
Some help would be welcome, since I am not familiar with the inner workings of tract or inferencing engines in general. Do you mean to implement the operator using some of the Gather* operators, when you write "as an Expansion"?
As I see it, I probably at least need an `array_feature_extractor` function in `ops/array/mod.rs` and register it in `register_all_ops`, correct?

**Comment by kali** [comment]
Yeah, register_all_ops is the entry point, indeed.

As for the `Expansion`, it's actually the name of the trait you will have to implement: you can grep `Expansion` in the code and you will find dozen of examples. Basically it means we will treat ArrayFeatureExtractor as a macro.

The Expansion trait implementation has two jobs: plug into the shape-and-type inference (that's the `rules` method) and translate the ArrayFeatureExtractor into an equivalent sub-network that use only `TypeOp` (the `wire` method).

**Comment by kali** [comment]
Making any progress here? Need more help?

**Comment by aeveris** [comment]
I'm sorry, I'm somewhat stuck on the `wire` method. It seems that many/most types in the hir layer have a counterpart in tract_core which then implements `TypedOp` and is used in `wire`. Should I also do that or is there something I'm missing here?

**Comment by kali** [comment]
You're right, what you need to do to implement the wire method is translate your operator as a TypedOp subnetwork. I think you can do it by just using one of the Gather Op from tract_core, so I don't think you will need extending tract_core : check out the Gather ops spec in onnx, I really think your operator is just a special case of one of them.

Tell me how it goes.
