### ISSUE TITLE
Ready for production?

### ISSUE THREAD

**Issue by fzyzcjy** [sonos/tract#579]
Hi thanks for the lib! I wonder whether it is ready for production?

**Comment by fzyzcjy** [comment]
Thanks! I want to use it in Android and iOS devices. Are they optimized and supported?

**Comment by kali** [comment]
Yes!

**Comment by fzyzcjy** [comment]
Thanks! I have not seen much NEON code for optimization, could you please give some hints?

**Comment by kali** [comment]
tract has good support for both armv7 NEON and aarch64 "advanced SIMD". code is in https://github.com/sonos/tract/tree/main/linalg .

One thing that may be missing is NEON detection on android armv7.

**Comment by fzyzcjy** [comment]
@kali Thank you!
