### ISSUE TITLE
Long processing times

### ISSUE THREAD

**Issue by CharlieBickerton** [sonos/tract#587]
Hey guys,

We've found that our code was taking quite a long time to run and we've investigated what was taking up the processing time. 

It seems that our model deployed through tract is a major cause. Have you guys been able to optimise model processing times internally? Have deployed quantised models before? 

Any info would be greatly appreciated.
Thanks!

**Comment by kali** [comment]
Hello!

We have done some optimisation work for quantised models, but not as much as on the f32 case. Are you comparing to another NN engine ? Which platform are we talking about ? What kind of net ? Would you be able to share the model with me ? Are you able to run the CLI on that platform to get a profile of your network ?

**Comment by kali** [comment]
Sorry mate, I have to close this. Feel free to reopen if you can provide us more details that we can act upon.
