### ISSUE TITLE
Performance comparison with tch-rs, onnxruntime-rs

### ISSUE THREAD

**Issue by rhobro** [sonos/tract#604]
Hi there.

I was wondering which library I should use for inference of a pytorch model exported to ONNX in Rust.

As far as I know, the options are
 - tract
 - [onnxruntime-rs](https://github.com/nbigaouette/onnxruntime-rs)
 - [tch-rs](https://github.com/LaurentMazare/tch-rs) (just running the model in pytorch itself)

How does inference performance compare with these two libraries?

Will tract support training models at some point?

Thanks

**Comment by kali** [comment]
Hi, thanks for your interest in tract.

* performance, hard to say out of the blue. if you're targetting arm64 or arm, chances are tract is faster. on x64, onnxruntime will probably be faster. That said, it may also depend on the model. No idea about tch-rs. Note that tract is also missing some of the most exotic operators in ONNX, while onnxruntime is supposed to have complete support of all the dark corners.
* tract will probably never be a training framework

**Comment by rhobro** [comment]
Thank you for your reply.

Out of interest, is tract multi-threaded and so on? In the overall graph, can it perform branches in parallel where possible?

Ok. Please could you recommend a training framework in rust?

Thanks

**Comment by kali** [comment]
tract is mono-threaded, but can be used in multi-threaded context (enabling to share a single model between multiple threads for instance).

There is a discussion https://github.com/sonos/tract/issues/342 here about possible multithreaded.

I don't know much about training. Our teams use a mix of pytorch and tensorflow (in python). In rust, there was something called leaf a few years ago but it has been abandonned.

**Comment by rhobro** [comment]
Correct me if I'm wrong but is the focus of tract on embedded and low-resource devices because it is designed to be used in Sonos products? That is so cool.

I was asking about training since the environment I am building is in Rust and I wanted to avoid having to implement that same environment in python so that I can train the model.

**Comment by kali** [comment]
I'm afraid the duplication between python for training and rust for inference is a bit of a curse we all have to deal with. Our teams here. People in our research teams like python because it has lots of libraries and because it is easier (guess this can be a matter of taste). After something has been "distilled" and ported in rust (typically feature extractors and post-processors), we sometimes use these brick in the training pipeline through ffi bindings.

**Comment by rhobro** [comment]
Would it be ok to import the rust code into python by compiling it to a .so?

**Comment by kali** [comment]
yeah, this is what we are doing, but you need FFI finding (or direct libpython bindings)

**Comment by rhobro** [comment]
Ok. Thank you. One final question;

So tch-rs appears to be bindings to libtorch. Are inference runtimes such as tract and onnxruntime faster than just using the ml library?

**Comment by kali** [comment]
I don't know for sure, but I would expect them to be. They are also easier to deploy.

**Comment by rhobro** [comment]
That's good to hear. Thank you very much
