### ISSUE TITLE
Onnx model fails loading in wasm build only

### ISSUE THREAD

**Issue by chriamue** [sonos/tract#605]
Hi there.

I try to run this model from the onnx model zoo: https://github.com/onnx/models/tree/master/vision/body_analysis/ultraface

```rust
type ModelType = SimplePlan<TypedFact, Box<dyn TypedOp>, Graph<TypedFact, Box<dyn TypedOp>>>;
pub fn model() -> ModelType {
        let data = include_bytes!("../assets/version-RFB-640.onnx");
        let mut cursor = Cursor::new(data);
        let model = tract_onnx::onnx()
            .model_for_read(&mut cursor)
            .unwrap()
            .with_input_fact(
                0,
                InferenceFact::dt_shape(f32::datum_type(), tvec!(1, 3, 480, 640)),
            )
            .unwrap()
            .into_optimized()
            .unwrap()
            .into_runnable()
            .unwrap();
        model
    }
```

In a non wasm build it works, but in a wasm build it crashes:

```sh
wasm-pack test --node
...
error output:
        panicked at 'called `Result::unwrap()` on an `Err` value: Building node  (Slice)
        
        Caused by:
            Node  (Slice), attribute 'ends': expected list of ints <= 2147483647, got 9223372036854775807', src/lib.rs:30:1
```

Line 30 of lib.rs is https://github.com/lenna-project/ultraface-plugin/blob/8ef92686087700a6b83567574fde9a18e8e7de22/src/lib.rs#L30

```rust
        let model = tract_onnx::onnx()
            .model_for_read(&mut cursor)
            .unwrap()
```

I don't know if this is an allocation issue or anything else, maybe someone has an idea.

Thanks

**Comment by kali** [comment]
Thanks for your interest in tract !

I am currently a bit far from any computer to debug this thoroughly, I will be able to have a look next week. This could be  an overflow... but it is very likely a corner case of negative indexing.

(also not that your `ModelType` is just tract's TypedPlan, iirc)

**Comment by kali** [comment]
Find a few minutes to make a temptative fix for the i64 issue. You may, (or may not) hit another issue down the road that only appear in debug mode, I will investigate that one later.

**Comment by kali** [comment]
I guess i got confused the other day between what was stashed and what was not. Anyway, pushed the right commit now on #606 .

**Comment by chriamue** [comment]
Happy new year!
Works like a charm:
![Screenshot from 2022-01-03 13-20-28](https://user-images.githubusercontent.com/7541795/147929845-c4009f3c-5edd-4746-973f-d008f99b63b8.png)
You can close this issue after merge.

**Comment by kali** [comment]
thanks !
