### ISSUE TITLE
Feature request: onnx coordinate_transformation_mode: asymmetric

### ISSUE THREAD

**Issue by chriamue** [sonos/tract#608]
Hi,
I tried to run the popular yolo model.
https://github.com/onnx/models/tree/master/vision/object_detection_segmentation/tiny-yolov3
my app crashes at 
[            s => todo!("coordinate_transformation_mode: {}", s),](https://github.com/sonos/tract/blob/c4f6936feea2053e83be70f8fb5489e8451e10b4/onnx/src/ops/resize.rs#L14)
returning
```
thread 'tests::default' panicked at 'not yet implemented: coordinate_transformation_mode: asymmetric', src/ops/resize.rs:14:18
```
Thanks in advance.

**Comment by chriamue** [comment]
I could find some documentation here https://github.com/onnx/onnx/blob/master/docs/Operators.md#attributes-72
```
if coordinate_transformation_mode is "asymmetric",
x_original = x_resized / scale,
```

**Comment by chriamue** [comment]
Hi, please check this pull request:
https://github.com/sonos/tract/pull/609
and give me advice how to properly test it.
I just rerun loading of the yolo model, which crashes now 
`panicked at 'not yet implemented: mode: nearest'`
here
```rust
    let interpolator = match node.get_attr("mode")? {
        "linear" => Interpolator::Linear,
        s => todo!("mode: {}", s),
    };
```

**Comment by chriamue** [comment]
Just saw, this merge request adds asymmetric too https://github.com/sonos/tract/pull/537

**Comment by chriamue** [comment]
Thanks for your guidance.

**Comment by kali** [comment]
thanks for the contribution :)
