### ISSUE TITLE
`Output mismatch after rewiring expansion` for `StridedSlice` node

### ISSUE THREAD

**Issue by golmschenk** [sonos/tract#630]
Hello!

I seem to be having an issue with a `StridedSlice` node, which seems to be on the list of nodes that `tract` supports. The specific error I'm encountering is:
```
Error: Translating node #1695 "StatefulPartitionedCall/lira/residual_generation_light_curve_network_block_16/cropping1d_4/strided_slice" StridedSlice ToTypedTranslator

Caused by:
    0: translating op StridedSlice { optional_axes_input: Some(3), optional_steps_input: None, begin_mask: 0, end_mask: 0, shrink_axis_mask: 0 }
    1: Output mismatch after rewiring expansion for output #0: expected 1,64,64,F32 got 1,64,128,F32
```

This occurs when trying to load the model:
```
let model = tract_onnx::onnx()
    .model_for_path("check.onnx")?
    .with_input_fact(0, InferenceFact::dt_shape(f32::datum_type(), tvec!(1, 11, 1)))?
    .into_optimized()?
    .into_runnable()?;
```

Just as confirmation, the model does not run into issues when used with the Python `onnxruntime`:
```
import numpy as np
import onnxruntime
import numpy
session = onnxruntime.InferenceSession("check.onnx")
input_node_name = session.get_inputs()[0].name
output_node_name = session.get_outputs()[0].name
random_input = numpy.random.random(size=[1, 11, 1]).astype(np.float32)
prediction = session.run([output_node_name], {input_node_name: random_input})[0]
print(prediction)
```

Here is the model used in the example: [model](https://drive.google.com/file/d/1yjF-nWOtFn1ix76i3eCbpTm60Msv465x/view?usp=sharing)

Please let me know if there's any other information that would be useful to diagnose the issue. Thank you for your time!

**Comment by kali** [comment]
Thanks for the report, it does look like a bug indeed. I tried to look at the model you linked, but it looks like a tf2 model, not an onnx one. Can you link check.onnx instead ?

**Comment by golmschenk** [comment]
Oh, my mistake! Uploaded the wrong thing. Here is the ONNX model: [ONNX model](https://drive.google.com/file/d/1UCSIXBOVhOhc8MRuyhMdRUH92pZwhQIY/view?usp=sharing)

Thank you for your time!

**Comment by kali** [comment]
@golmschenk interestingly, it looks like the bug is not reproducable with the current top of tree (while my first attempt with a 0.15.7 reproduced). Can you check against the top of tree too and tell me if it's better ? I can probably cut a release if that is the case.

**Comment by golmschenk** [comment]
@kali, indeed, I can confirm that using the GitHub repository directly as the dependency appears to resolve the issue. I apologize for not checking this originally! Just for reference, the version I was using that appears to have the issue seems to be `0.15.8`. And I should note, for my own purposes, I don't have a problem with pointing to the GitHub repository directly, rather than a version. So for me at least, there is no hurry to push out a release. I'll leave the issue open in case you want to keep it up until the release, but I consider it resolved, so feel free to close it. Thank you very much!
