### ISSUE TITLE
NNEF conversion fails when reshape depends on Batch Dimension

### ISSUE THREAD

**Issue by tgolsson** [sonos/tract#718]
When attempting to convert a model from https://github.com/Lednik7/CLIP-ONNX I get the following error:

```
$ tract image.onnx -i N,3,224,224,f32 --nnef-tract-core --nnef-tract-onnx dump --nnef-tar image.nnef.tar
[2022-05-17T13:23:05.692388987Z ERROR tract] Translating node #104 "Reshape_97" Reshape ToTypedTranslator

    Caused by:
        0: translating op Reshape
        1: shape input is variable
```

If I fix the dimension (`-i 1,3,224,224,f32`) it works fine. Looking in the output when it succeeds, this is the offending op:

```
...
┃┣┓
┃┃┣ 29 MatMulUnary MatMul_69.split-m.0..768
┃┃┣ 30 AddUnary Add_70.Slice_81.axis2_0_768
┃┃┣ 31 Reshape Reshape_97.0
┃┃┃   ━━━ 50,84,64,F32
┃┃┣ 32 MoveAxis Transpose_98.MoveAxis-0
┃┃┃   ━━━ 84,50,64,F32
┃┃┣ 33 MulUnary Div_127
┃┣━┓
...
```

Where I specialized for N=7, and the *second* dimension of the reshape depends on the batch size. (7 * 12 = 84).

The files are huge but should be able to share them via mail/Drive if you want to investigate.

**Comment by tgolsson** [comment]
This seems to occur when calling `to_typed()` on the model specifically, unrelated to NNEF conversion.

**Comment by kali** [comment]
Hey, thanks for the report.

So what we encountered is a reshape from: `50,N,12,64` to `50,12N,64` ?

hint: `dump --io-long` will show all input and outputs types for all operators...

**Comment by kali** [comment]
Yeah, had a look at it, I think I will need the model. You know how to reach me.

**Comment by tgolsson** [comment]
Hey, shared the model with you over Drive since it's quite big. I included another model  (`text.onnx`) which also fails to convert and does similar permutes, but the error message is about inplace uniforms. The input fact used there is `-i N,77,i32`. Not sure if related, or if you want me to open a separate issue for that.

**Comment by kali** [comment]
I'll have a look later this week, things are a bit hectic over there. Don't create a separate issue, it's probably the same thing, or in the same vicinity.

**Comment by kali** [comment]
Made some progresses, but there are multiple issues. See branch fixes-for-718 if you're curious.

**Comment by kali** [comment]
Think I got it. Three different issues stacked on top of each other here, just for this model, so... I guess you're pushing the enveloppe pretty hard. Thanks for your patience :)

**Comment by kali** [comment]
@tgolsson did you get a chance to check on that one ? You've been pretty busy I guess, but...

**Comment by kali** [comment]
Yeah, please make it a PR, I'll point you in the right direction or take it from there.
