### ISSUE TITLE
failed to decode Protobuf message: GraphDef.node: invalid wire type: Varint (expected LengthDelimited)

### ISSUE THREAD

**Issue by nathanbabcock** [sonos/tract#750]
I am running the same saved model in the full Rust `tensorflow` crate, and it loads and works perfectly. Loading it in `tract-tensorflow` gives this error:

```
thread 'tensorflow' panicked at 'called `Result::unwrap()` on an `Err` value: Reading proto model

Caused by:
    failed to decode Protobuf message: GraphDef.node: invalid wire type: Varint (expected LengthDelimited)', src\tensorflow.rs:52:48
```

Does this indicate Tract is not compatible or up to date with the version of SavedModel that I'm using?

**Comment by kali** [comment]
tract accepts TF1 "frozen" models, not the more recent saved model format. Support for ONNX is much better: It may be easier to translate the TF saved model to ONNX, then load the ONNX model in tract.

**Comment by nathanbabcock** [comment]
> tract accepts TF1 "frozen" models, not the more recent saved model format. Support for ONNX is much better: It may be easier to translate the TF saved model to ONNX, then load the ONNX model in tract.

Thank you, this is really good to know! I'll try ONNX instead.
