### ISSUE TITLE
Next release timeline?

### ISSUE THREAD

**Issue by tgolsson** [sonos/tract#758]
Hello!

We've narrowed down a significant memory leak in our ML tooling to the fix in e515158842cdc6cb9341481a325ea3cbe9e38bd3. I'm wondering if you have any plans for when the next release will happen; in case I can avoid running a git patch.

Thanks!

**Comment by kali** [comment]
Will do one today or tomorrow.

**Comment by tgolsson** [comment]
Thank you!

**Comment by kali** [comment]
Done!
