### ISSUE TITLE
Error compiling `fullfp16` kernels on Mac arm64

### ISSUE THREAD

**Issue by tgolsson** [sonos/tract#763]
Heyo!

Upon upgrading tract to 0.17.1 our CI goes boom when building the fp16 kernels on M1 with the following error:

```
xxx/target/aarch64-apple-darwin/debug/build/tract-linalg-257a32b3c5858380/out/arm64fp16_mmm_f16_16x8_a55.S:2161:5: error: instruction requires: fullfp16
  | cargo:warning=    fmla v31.8h, v1.8h, v4.h[7]
  | cargo:warning=    ^
  | exit status: 1
  |  
  | --- stderr
  |  
  |  
  | error occurred: Command "cc" "-O0" "-ffunction-sections" "-fdata-sections" "-fPIC" "-g" "-fno-omit-frame-pointer" "-arch" "arm64" "-static" "-Wall" "-Wextra" "-o" "xxx/target/aarch64-apple-darwin/debug/build/tract-linalg-257a32b3c5858380/out/arm64fp16_mmm_f16_128x1_a55.o" "-c" "xxx/target/aarch64-apple-darwin/debug/build/tract-linalg-257a32b3c5858380/out/arm64fp16_mmm_f16_128x1_a55.S" with args "cc" did not execute successfully (status code exit status: 1).
```

This occurs both when building tract, and when compiling the kernel manually with both clang13 and clang14. My current working assumption is that there's a missing or incorrect flag; but I can't coax clang14 to even admit there's a feature called `fullfp16`, though `llc-14` knows about it for aarch64. As far as I can tell the instruction should work on the target architecture, it's just a matter of figuring out the proper flags to pass.

**Comment by kali** [comment]
I'm pondering doing a CI cross build for Apple silicon too.

**Comment by kali** [comment]
And will redo a release too.

**Comment by tgolsson** [comment]
Thanks!

I had a look at that branch setup but I couldn't get other `-mcpu` values to compile (e.g. `-mcpu apple-m1`). Does that change "fix it" by just delegating the check to runtime for clang targets? Is the implication that clang just is broken for cpu features for apple-m1?

**Comment by kali** [comment]
I just think clang needs a nudge in the right direction to accept extensions (fullfp16 is armv8.2, not armv8). gcc is happy with just the mention https://github.com/sonos/tract/blob/main/linalg/arm64/arm64fp16/arm64fp16_mmm_f16_16x8_core.tmpl#L26.

This is not breaking anything in tract here, this is assembly, it gets translated or it does not...

What /is/ broken, IIRC, is https://docs.rs/cc/latest/cc/struct.Tool.html#method.is_like_clang. I think it says "no" whan the compiler name is "cc" or something like that.

**Comment by kali** [comment]
FYI 0.17.2 done

**Comment by tgolsson** [comment]
Yepp, upgraded with success now! Thanks a lot for quick turnaround.

FWIW re the mcpu mystery; seems like setting `-mcpu=apple-m1` inside the build.rs does work; but overriding it on the command line from a failing build doesn't work. I'm guessing there's some env setup that I don't get  when running manually. I guess it doesn't really matter for the kernels as long as ISAs are forward-compatible (m1 is armv8.5).
