### ISSUE TITLE
Investigate M1 support for f16.

### ISSUE THREAD

**Issue by kali** [sonos/tract#765]
M1 seems to be armv8.5. So fp16 should be there and should be activated.

**Comment by jinfagang** [comment]
Same proposal here.

**Comment by kali** [comment]
Feel free to try the linked branch. Should work, but I still want to see what I can achieve wrt CI.

**Comment by jinfagang** [comment]
@kali awesome. BTW, it looks like tract use arm instrinces SIMD to do massive vector compute, then just wonder how's the exactly efficiency compared with some C++ infer lib such as ORT, mnn, ncnn etc. (I mainly focus on CV scenarios, like mobilenetv2, shufflenetv2 etc)
