### ISSUE TITLE
Does tract using SIMD instructions to accelerate compute?

### ISSUE THREAD

**Issue by jinfagang** [sonos/tract#768]
If so, how? How to using SIMD instructions in rust?

**Comment by kali** [comment]
tract-linalg features hand-crafted assembly code for matrix multiplication and the common activation functions, targetting arm32, arm64 and intel.

To answer the more general question, beyond assembly, external and inline, rust also has intrinsics for this platforms. Also nightly has a portable-simd feature (which then relies on LLVM for translation to proper machine code).
