### ISSUE TITLE
onnx-mobilenet-v2 example not working

### ISSUE THREAD

**Issue by stellanhaglund** [sonos/tract#832]
Example not working, getting. 

```
Error: Failed analyse for node #212 "Gemm_104" Gemm

Caused by:
    0: Infering facts
    1: Applying rule inputs[0].shape[0] == outputs[0].shape[0]
    2: Impossible to unify Val(1) with Sym(Symbol('b', 0)).
```

**Comment by kali** [comment]
Thanks for reporting this. It's an unfortunate consequence of a fix we did a couple of weeks ago. Will fix it ASAP.

**Comment by stellanhaglund** [comment]
Thats nice!

Not sure if its related but I also got an error with v2-12 about clip, not
sure if that is related or if that version isn’t supported?

mån 10 okt. 2022 kl. 19:24 skrev Mathieu Poumeyrol ***@***.***

**Comment by kali** [comment]
Will handle 2.12 problem separately.
