### ISSUE TITLE
Unnecessary copy of inputs

### ISSUE THREAD

**Issue by mbrunel** [sonos/tract#845]
Hello,

In the run method of Simpleplan, the inputs parameter is a TVec<Tensor>. Since the tensors eventually get converted into an Arc<Tensor>, it means each input tensor get copied once.

Of course this doesn't matter most of the time because the input is small enough, but we have a use case in which the inputs would be huge and reused between differents runs.

Therefore I was wondering if it is possible to allow the user to pass a TVec<Arc<Tensor>> to the run method, hence avoiding the later conversion. In the case you don't want to change the API, there is also the option of adding a new run_with_arcs method that would have the same effect.

If you agree with one of the two possibilities, I can do the corresponding PR shortly as there is almost nothing to do.

wdyt?

**Comment by kali** [comment]
Please check out my comment over there https://github.com/Rikorose/DeepFilterNet/pull/13#issuecomment-1237262459 

But we can discuss it. Even for the sake of making sure people stop freaking out about it ;)
