### ISSUE TITLE
`Greater` does not support `TDim`

### ISSUE THREAD

**Issue by guillaume-be** [sonos/tract#856]
Hello,

I am trying to run a model that was exported for ONNX-runtime via the [optimum](https://huggingface.co/hardware)'s library. I am specifically trying to load the models that are made available at https://huggingface.co/optimum/t5-small/tree/main:

```rust
use std::path::Path;
use tract_onnx::prelude::*;

fn main() -> anyhow::Result<()> {
    let encoder_path = Path::new("path/to/t5-small/encoder_model.onnx");
    let decoder_path = Path::new("path/to/t5-small/decoder_model.onnx");
    let decoder_with_past_path = Path::new("path/to/t5-small/decoder_with_past_model.onnx");

    let encoder_model = onnx().model_for_path(encoder_path)?.into_runnable()?;

    let input_ids: Vec<i64> = vec![8774, 48, 19, 3, 9, 182, 307, 1499, 12, 36, 15459, 5, 1];
    let attention: Vec<i64> = vec![1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1];

    let input_ids =
        tract_ndarray::Array2::from_shape_vec((1, input_ids.len()), input_ids.clone())?.into();
    let attention_mask =
        tract_ndarray::Array2::from_shape_vec((1, attention.len()), attention)?.into();

    let model_inputs = tvec!(input_ids, attention_mask);
    let result = encoder_model.run(model_inputs)?;

    println!("{:?}", result);

    Ok(())
}
```
returns:
```
Error: Evaluating #187 "Greater_67" Greater

Caused by:
    0: Evaluating #5 "adhoc" Greater
    1: Greater does not support TDim
```

I also tried to made the model `into_optimized`:
```rust
    let encoder_model = onnx()
        .model_for_path(encoder_path)?
        .into_optimized()?
        .into_runnable()?;
```
I then get the following error:
```
Error: Failed analyse for node #209 "Min_89" MinNary

Caused by:
    0: Infering facts
    1: Applying rule inputs[0].datum_type == inputs[1].datum_type
    2: Impossible to unify TDim with I64.
```

Is this model leveraging an operator that is not supported in Tract?

**Comment by kali** [comment]
Haha, thanks for the detailed test case! I think I should be able to make it work.

TDim is actually the problem here, but I know how to make it work. I will have a look.

**Comment by kali** [comment]
Hello, I thought there may be a problem around Greater indeed... but your test case does not seem to reproduce it (tested on top of tree and on 0.18.3, with or without the into_optimized() call). Can you confirm it ?

**Comment by guillaume-be** [comment]
Hello @kali ,
I confirm I am facing the issue with `tract-onnx=0.18.3` with the file downloaded from https://huggingface.co/optimum/t5-small/resolve/main/encoder_model.onnx. I just tried a fresh compilation of the project and still encounter the error.

**Comment by kali** [comment]
Yeah sorry, very stupid cut and paste mistake :)

**Comment by kali** [comment]
Hello @guillaume-be, could you give a shot at the linked branch ? There was several smallish issues around type inference in the context of n-ary operators, but it seems to work now.

**Comment by guillaume-be** [comment]
Hello @kali,
Yes - it looks like it is now working on the main branch. thank you for the quick turnaround!
