### ISSUE TITLE
Error during einsum pack

### ISSUE THREAD

**Issue by Rikorose** [sonos/tract#857]
Relevant tract error:
```
Error: Evaluating #30 "Einsum_71.mm.pack" MatMatMulPack

Caused by:
    Invalid prefix [0, 0, 1] for shape [1, 32, 1, 32]
```

Not sure what the issue is here, since similar models do work (same python code for onnx export, same rust code). [This model](https://github.com/sonos/tract/files/9901748/df24k.zip) also works when using the [tact cli](https://github.com/Rikorose/DeepFilterNet/blob/main/scripts/test_model_tract_cli.sh), but fails during `run()` when I call [from rust](https://github.com/Rikorose/DeepFilterNet/blob/main/libDF/src/tract.rs#L355).

Some background. I have a grouped linear layer, which essentially splits up the input dimension into `g` groups so that we have a smaller matmul:
```py
b, t, _ = x.shape
x = x.view((b, t, self.groups, self.ws))
x = torch.einsum("btgi,gih->btgh", x, self.weight)
```
where b: batch size, t: time, g: number of groups, i: input size, h: hidden size

Tract works e.g. with `g=8, i=384` (that is DeepFilterNet2), or with `g=4, i=64`, but it fails with `g=8, i=32`.

Relevant tract cli usage:
```bash
tract -v \
  enc.onnx \
  --onnx-ignore-output-shapes \
  -i 1,1,S,16,f32 -i 1,2,S,16,f32 \
  --pulse 1 run \
  --input-from-bundle enc_input.npz \
  --assert-output-bundle enc_output.npz \
  --save-outputs enc_output_tract.npz
```

Relevant rust call:
```rust
dbg!(tvec!(
    self.erb_buf.clone(),
    self.cplx_buf.clone().permute_axes(&[0, 3, 1, 2])?
));
let mut enc_emb = self.enc.run(tvec!(
    self.erb_buf.clone(),
    self.cplx_buf.clone().permute_axes(&[0, 3, 1, 2])?
))?;
```

```bash
cargo run -p deep_filter --features bin,tract,wav-utils,timings --bin deep-filter -- --model /tmp/export/df24k_onnx.tar.gz ./assets/noisy_snr0.wav -D
    Finished dev [optimized + debuginfo] target(s) in 0.13s
     Running `target/debug/deep-filter --model /tmp/export/df24k_onnx.tar.gz ./assets/noisy_snr0.wav -D`
[libDF/src/tract.rs:355] tvec!(self.erb_buf.clone(), self.cplx_buf.clone().permute_axes(& [0, 3, 1, 2])
    ?) = [
    1,1,1,16,F32 -0.34727335, -0.26391298, -0.2275528, -0.2726429, -0.39620265, -0.45310822, -0.37631398, -0.31352654, -0.29521352, -0.30341205, -0.30904254, -0.33192807...,
    1,2,1,16,F32 -0.0061971853, -0.0014425786, 0.0066401972, 0.006862815, -0.0011913456, -0.007273956, -0.0050168983, 0.0009246279, 0.0032268267, 0.0010799235, -0.0014782848, -0.0017244084...,
]
Error: Evaluating #30 "/df_fc_emb/0/Einsum.mm.pack" MatMatMulPack

Caused by:
    Invalid prefix [0, 0, 1] for shape [1, 32, 1, 32]
```

Edit:
Replacing the einsum by a manual matmul in pytorch works:
```py
x = torch.matmul(x.unsqueeze(3), self.weight).squeeze(3)
```

**Comment by kali** [comment]
Hello, I confirm I can reproduce the problem. The reason why it fails in code and works in command-line seems to be because you do not pass  `-O` in the cli call (so model is ran in decluttered form, not in optimised form).

Hunting down the root cause.

**Comment by kali** [comment]
@Rikorose I think I have it...
