### ISSUE TITLE
jupyter-keras-tract-tf2: Error: Failed analyse for node #10 "Sigmoid" Sigmoid

### ISSUE THREAD

**Issue by dhdaines** [sonos/tract#877]
Following the instructions in `examples/jupyter-keras-tract-tf2/README.md` from the `main` branch, I get this error from `cargo run` after training the model with the Jupyter notebook:

```
Error: Failed analyse for node #10 "Sigmoid" Sigmoid

Caused by:
    0: Infering facts
    1: Applying rule inputs[0].shape == outputs[0].shape
    2: Unifying shapes 10,1 and N,1
    3: Impossible to unify Val(10) with Sym(N).
```

Being a total beginner with tract I'm not sure where to look to solve the problem, let me know if there's any other information you need!

**Comment by kali** [comment]
Try to remove line 9 in the example ? The with_input_fact call is probably the problem now (tract can now handle onnx symbolic shapes, so overriding the input shape is counter productive).

**Comment by dhdaines** [comment]
Yes, that's exactly it, thanks!
