### ISSUE TITLE
Error occurred during optimization

### ISSUE THREAD

**Issue by maekawatoshiki** [sonos/tract#962]
Hello!
I tried the [onnx mobilenet example](https://github.com/sonos/tract/tree/main/examples/onnx-mobilenet-v2) and it worked fine.
However, the example code raised an error below when running a [DeiT model](https://huggingface.co/docs/transformers/model_doc/deit) exported to onnx.
(It seems the error occurred on this line https://github.com/sonos/tract/blob/bd5c8c2fdffdb79edc227cb41f8e1a26107ec44d/core/src/ops/array/slice.rs#L85)

```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: running pass PropConst

Caused by:
    0: Eager eval #131 "Add_95.split-0-over-1.1..197.slice" Slice during optimisation
    1: Invalid range 1..197 for slicing 1,1,384,F32 0.024051493, 0.15479629, -1.1061088, 0.8805294, -0.017479805, 0.37792578, 0.061502736, 0.5711508, -0.13008586, 0.99071044, 0.16245633, 0.11184703... on axis 1', examples/onnx-mobilenet-v2/src/main.rs:10:27
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

By turning off optimization (removing `onnx_model.into_optimized()`), the model runs fine.
I'm not sure how to fix this problem.

**Comment by kali** [comment]
Hey, thank for your interest in tract.

Can you give me the ONNX model ? if it helps, mail is `mathieu dot  <last name> at sonos dot com`

**Comment by maekawatoshiki** [comment]
The model is here (google drive): https://drive.google.com/file/d/1Xg7ALNVB6Xp8REY9dNz5YqQjsbG9T0mG/view?usp=sharing

**Comment by kali** [comment]
Thanks. This is definitely a bug. I will be working on a fix in the next couple of days.

**Comment by maekawatoshiki** [comment]
I verified that the problem is now fixed! Thank you.
