### ISSUE TITLE
Failed to load tensorflow model converted with tf2onnx

### ISSUE THREAD

**Issue by hdtrinh** [sonos/tract#964]
I can't load a tensorflow model converted with tf2onnx. Since [keras2onnx](https://github.com/onnx/keras-onnx) (used in the examples) is deprecated, I've been using tf2onnx.  I've encountered this problem starting from tract 0.18. 

```
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: Failed analyse for node #14 "model_dense_2_BiasAdd" Add

Caused by:
    0: Infering facts
    1: Applying rule outputs[0].shape == unk__6,90
    2: Unifying shapes unk__7,90 and unk__6,90
    3: Impossible to unify Sym(unk__7) with Sym(unk__6).'
```
Model is the following: [model.zip](https://github.com/sonos/tract/files/10723590/model.zip)

**Comment by kali** [comment]
Hello, thanks for your interest in tract!

Your model use placeholders in "free" variables (unk__6 and unk__7) in input shapes and outputs shapes. It ignores the fact that they are related (they are even equal). As tract tries to makes sense of the shapes, it's unhappy that they don't match.

The easy fix is to ignore the output shape. On the command line you can use `--onnx-ignore-output-shapes`. On the API, call `with_output_fact(0, Default::default())` on the model right after loading the model, before `into_optimized()`.

**Comment by kali** [comment]
Which examples was that by the way ? the jupyter keras one ?

**Comment by hdtrinh** [comment]
Yes, [jupyter-keras-tract-tf2](https://github.com/sonos/tract/tree/main/examples/jupyter-keras-tract-tf2).  Ignoring the output shape solved the problem, thank you for your amazing work!
