### ISSUE TITLE
ReduceMean error during optimization

### ISSUE THREAD

**Issue by acrrd** [sonos/tract#976]
Moving from tract `0.18.5` to any `0.19` we have the following error when optimizing the model.

```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: running pass PropConst

Caused by:
    0: Eager eval #32 "ReduceMean_20.norm.split-1-over-1.1..64.slice" Slice during optimisation
    1: Invalid range 1..64 for slicing 1,1,1,F32 0.0078125 on axis 1', src/main.rs:29:28
```

You can reproduce the error with the code and model here: https://github.com/xaynetwork/tract_reduce_mean
We have been using this model with tract for the past year and a half across multiple versions, so I think is more a regression than a problem with the model.

**Comment by kali** [comment]
I think this one is fixed on main, and I have actually ported what I think is the fix on the 0.19.x branch this very morning. Would you be kind enough to b2d394cf7b61da6d7cc3182fef1c2ad8f6401532 and tell me if it fixes it ?

**Comment by acrrd** [comment]
It fixes it; thank you very much for your prompt reply!

**Comment by kali** [comment]
Thanks. 0.19.3 will come very soon. Maybe today.
