### ISSUE TITLE
MultiBroadcastTo ToTypedTranslator

### ISSUE THREAD

**Issue by stellanhaglund** [sonos/tract#985]
Hello, I'm not sure if I did something wrong or where I should debug this, but I get this error. 

Error: Translating node # 24 "sequential_lstm_zeros" MultiBroadcastTo ToTypedTranslator

Caused by:
    0: translating op MultiBroadcastTo
    1: shape input is variable

When using a model that looks like this

```
model = Sequential()
model.add(Conv1D(conv1d_filters, 12,strides=conv1d_strides, activation=None, padding='same',input_shape=(input_size,1)))
model.add(Conv1D(conv1d_filters, 12,strides=conv1d_strides, activation=None, padding='same'))
model.add(LSTM(hidden_units))
model.add(Dense(1, activation=None))
model.compile(optimizer=Adam(learning_rate=learning_rate), loss=error_to_signal, metrics=[error_to_signal])
```

Here's the rust part
```
    let model = tract_onnx::onnx()
        // load the model
        .model_for_path("./guitar.onnx")?
        .with_output_fact(0, Default::default())?
        // optimize graph
        .into_optimized()?
        // make the model runnable and fix its inputs and outputs
        .into_runnable()?;
```

**Comment by kali** [comment]
Hello, thanks for your interest! 

Can you share the ONNX file ?

**Comment by stellanhaglund** [comment]
hey! yeah sure, here is the file!
[guitar.onnx.zip](https://github.com/sonos/tract/files/10869275/guitar.onnx.zip)

**Comment by kali** [comment]
Hello, there were actually several issues, all of them in tract. I hope I have fixed them all.

I would appreciate a validation if you can :)
