### ISSUE TITLE
No access to tech bolgs

### ISSUE THREAD

**Issue by ChangyouSiom** [sonos/tract#999]
Hi  kali @kali
  I want to read the tech blogs as you list in the README, but no access to them. 
  Could you help me? Thanks a lot!

**Comment by kali** [comment]
No access to https://tech-blog.sonos.com/ ? Is this a China firewall issue ?

**Comment by JackKCWong** [comment]
Access Denied
You don't have permission to access "http://tech-blog.sonos.com/" on this server.
Reference #18.158c941b.1678894164.f6c1f7

looks like sth on the sono server.

**Comment by kali** [comment]
Investigating what's wrong with the blog may take a while. In the meantime...

[The anatomy of efficient matrix multipliers | Sonos Tech Blog.pdf](https://github.com/sonos/tract/files/10983974/The.anatomy.of.efficient.matrix.multipliers.Sonos.Tech.Blog.pdf)
[Optimising a neural network for inference | Sonos Tech Blog.pdf](https://github.com/sonos/tract/files/10983975/Optimising.a.neural.network.for.inference.Sonos.Tech.Blog.pdf)
[Assembly still matters: Cortex-A53 vs M1 | Sonos Tech Blog.pdf](https://github.com/sonos/tract/files/10983976/Assembly.still.matters.Cortex-A53.vs.M1.Sonos.Tech.Blog.pdf)
